<?php
// Program: content_mo_trng_grappling_fr.php
//	Description: source for the textual content on the grappling page (mo_trng_grappling.php) (« »)
//	2017 ------------------
///
// French content -------------------
$title[1] = "Lutte (abrazare)";

$trng_1_p1[1]	= "Il n'y a pas de meilleur moyen que d'utiliser le plus ancien style de combat du monde - le grappling <sup><a href=\"#1\" title=\"référence n° 1: grappling\">[1]</a></sup> ou <i>abrazare</i> pour transmettre les concepts de timing et de distance. Grappling est une forme de lutte, ce qui est indiscutablement, le plus ancien style de combat du monde, où les grapplers ont été dépeints sur les peintures murales égyptiennes il ya 5000 ans. Toutefois, les Grecs ont été ceux qui ont mis la lutte sur la carte de l'ancien monde, faisant ses débuts olympiques en 708 avant JC.";
$trng_1_p2[1]	= "Lutte formation commence avec un certain nombre de techniques de lutte contemporaine, comme une prise d'épaule, tenue de cou, tenue de la taille, serrures de la tête et des techniques pour sortir de ces cales. Cette approche offre une introduction simple à certaines des bases fondamentales de grappling et donne l'occasion aux étudiants de devenir plus à l'aise avec « l'homme-manipulation » leurs partenaires de formation et d'augmenter également leur confort avec être « l'homme-manipulation » se. Ces pratiques d'introduction contribuent également à développer un degré de confiance avec leurs partenaires de formation afin que lorsque les techniques plus sophistiquées Fiore sont roulés en formation, les étudiants sont bien conditionnés pour apprendre et pratiquer de nouvelles techniques avec leurs partenaires de formation avec un degré plus élevé de sécurité personnelle . Ces compétences qui sont apprises forment le fondement sur lequel d'autres compétences sont placées, comme les techniques de poignard et de longue épée. L'étudiant est alors initié aux techniques décrites dans le traité de Liberi. Il est essentiel que l'étudiant comprenne que les techniques apprises lors de la formation de grappling et la formation plus tard dague sont des techniques extrêmement dangereuses! L'étudiant doit rester conscient que son partenaire est exactement cela, un partenaire de formation, et pas quelqu'un pour concurrencer pendant les exercices d'entraînement. Dans le manuscrit de Liberi, il ya effectivement très peu d'exemples (quatre cas) dans lesquels il se réfère au partenaire comme un adversaire. L'étudiant voit son partenaire d'entraînement à la lumière d'un joueur (un <i>zugadore</i> (italien), d'un partenaire en formation) ou compagnon (un <i>compagno</i> (italien), un autre Référence à un partenaire dans une orientation non agressive).";
$trng_1_p3[1] = "L'élève à la fin de la partie de formation aura développé une bonne compréhension et une base de compétences dans le domaine des gardes (positions en préparation pour déployer des manœuvres défensives ou offensives) et commence à développer le concept de chronométrage, distance, jugement et Position et leur application aux combats. Les techniques avancées de grappling et de lancer décrites dans « jeux » par Fiore seront explorées en détail pendant la formation. ";
// array to store liberi images for shuffling in order to randomize the presentation of the images on this page
$liberi[0] = "grappling_1.jpg";
$liberi[1] = "grappling_2.jpg";
$liberi[2] = "grappling_3.jpg";
$liberi[3] = "grappling_4.jpg";
$liberi[4] = "grappling_5.jpg";
$liberi[5] = "grappling_6.jpg";
$liberi[6] = "grappling_7.jpg";
$liberi[7] = "grappling_8.jpg";
$liberi[8] = "grappling_9.jpg";
$about_trng_caption[1] = "Les images ci-dessus sont sélectionnées au hasard et présentent des folios (pages) à partir des différentes versions de Fiore dei Liberi's traités qui proviennent spécifiquement de MS Ludwig XV 13 (Getty), Pisani-Dossi MS et MSS Latin 11269 (BNF), à partir de laquelle l'Académie mène ses recherches et développe son programme de formation.";

$trng_l1[1]	= "Le combat se réfère à des techniques, des manœuvres et des compteurs appliqués à un adversaire afin d'obtenir un avantage physique dans le combat corps à corps, comme l'amélioration de la position relative, l'échappement, la soumission ou des blessures à l'adversaire. Grappling est un terme général qui couvre les techniques utilisées dans de nombreuses disciplines, styles et arts martiaux qui sont pratiqués à la fois comme des sports de combat et pour la légitime défense. Grappling le plus communément ne comprend pas la frappe ou l'utilisation d'armes. Cependant, certains styles de combat ou d'arts martiaux connus surtout pour leurs techniques de grappling enseigner des tactiques qui incluent des grèves et des armes soit à côté de grappling ou combiné avec elle. source : Wikipedia. <a href=\"https://fr.wikipedia.org/wiki/Grappling\" target=\"_blank\">Grappling</a>. consulté le : 17 janvier 2017.";
$trng_l2[1]	= "La date de création la plus largement acceptée pour les Jeux Olympiques Anciens est 776 avant JC (\"<a href=\"https://www.britannica.com/sports/Olympic-Games\" target=\"_blank\">Olympic Games</a>\". Encyclopædia Britannica. consulté le : 17 janvier 2017); il est basé sur des inscriptions, trouvées à Olympie, énumérant les gagnants d'une course à pied qui a lieu tous les quatre ans à partir de 776 avant JC. Les Jeux Anciens ont comporté des événements de course, un pentathlon (consistant en un événement de saut, des lancers de dents et de javelot, une course de pieds et de lutte), la boxe, la lutte, le pankration et les épreuves équestres. Selon la tradition, Coroebus, cuisinier de la ville d'Elis, était le premier champion olympique. source: Wikipedia. <a href=\"https://fr.wikipedia.org/wiki/Jeux_olympiques\" target=\"_blank\">Jeux olympiques</a>. consulté le : 17 janvier 2017.";

?>
