<?php
// Program: content_mo_rnk_scholler_en.php
//	Description: source for the English textual content on the detailed members only rank of scholler page (mo_rnk_scholler.php)
//	2017 ------------------
//
// English content -------------------
$title[0] 	= "Rank: Scholler";
$banner[0] 	= "<img src=\"../images/banner_scholler.jpg\" alt=\"\" width=\"100%\"/>";
$rnk_p11[0]	= "The rank of <b>scholler</b> identifies a student and practitioner of the historal European martial arts known as <i><b>l`arte dell`armizare</b></i> or simply as <b><i>armizare</i></b> and is one who has committed to learning and training in the art. The <b>scholler</b> recognizes that in order to become proficient in this art, as with any other martial arts systems, it is a life-style choice requiring the commitment and dedication necessary to achieve a level of excellence that will enrich the student's life both intellectually and physically. In order to achieve competency in the more advanced levels, the scholler must attempt to schedule him/herself accordingly to permit attending regular training sessions. The <b>scholler</b> must abide by the rules and constitution of the Academy, and be prepared to obtain the relevant historically accurate arms & armour for those weapons trained with. <b>Scholler</b> training is the longest and most intense of all the ranks.";
$rnk_p12[0]	= "It is during the <b>scholler</b> training where the student learns how to \"fight\" becoming both a knowledgable, skillful and competent martial artist.  The foundational principles learned and trained during the recruit training forms the basis on which advanced techniques and combative principles are built upon.  The training structure mirrors the format of Fiore dei Liberi's <a href=\"\" target=\"_top\"><i>Flos Duellatorum</i></a> in terms of training segments mapping to the fighting/weapons styles documented in the treatise.  The scholler will continue to train in the core training components (<i>abrazare, daga, spada</i>) of the recruit training program, but will delve into these segments in far greater depth.  These segments will be scheduled throughout the year, so that over time, a scholler will have the opportunity to train, practice and be tested in each of the segments. ";
$rnk_p13[0]	= "The scholler training program will encompass the following styles: <i>abrazare, daga, spada, spada e brocchiere, spada longa</i>, poleweapons: <i>azza e lanza</i>, and <i>arme</i> not necessarily in that order. <b>At the conclusion of the program, the scholler is tested by the instructors.</b>  If the scholler passes the <b>scholler test</b>, he/she will be awarded a rondel dagger representing the prize successfully completed. This rondel dagger can be worn by the scholler during training and events.";
$rnk_p14[0]	= "From a heraldic perspective, <b>schollers</b> are encouraged to become  \"<b>invested with arms</b>\" so that their coats of arms can be suspended on display on the armory rack at the salle d'armes to which the schollar badges can be attached represented the segments successfully completed, and in the form of flags or banners during their participation in tournaments (armoured and/or unarmoured) or other events if appropriate.  For examples of arms currently possessed by schollers and above, click <a href=\"\"><b>here</b></a>. There are a number of resources to assist in this matter, and it is imperative that the arms created, assumed, matriculated, registered, granted is heraldically correct and therefore, to that end, there are a good number of individuals in AEMMA that can offer assistance and guidance. Further information can be found at the bottom of this (<b>scholler</b>) section by clicking <a href=\"\"><b>here</b></a>.";

$title_p2[0] 	= "Scholler Requirements";
$rnk_l21[0]	= "has obtained the rank of <b>scholler</b> by successfully challenging and completing the <a href=\"javascript:schollerTest()\" title=\"Click to peruse a sample scholler test\"><font color=\"#461B7E\"><b>scholler test</b></font></a>,";
$rnk_l22[0]	= "<a href=\"\">training dues</a> are paid for on a regular basis and there are no outstanding dues,";
$rnk_l23[0]	= "possesses the <a href=\"\">minimum equipment</a> as required for the <b>scholler</b> rank,";
$rnk_l24[0]	= "has taken the initiative with respect to being \"invested with arms\" which have been approved by AEMMA or <a href=\"http://www.gg.ca/heraldry\" target=\"_blank\">CHA</a>, click <a href=\"#heraldry\"><img src=\"../images/coatofarms/tinyShield.gif\" valign=\"middle\" hspace=\"4\" border=\"0\" alt=\"\" class=\"fade\" title=\"Click to learn more about obtaining a personal coat of arms\"></a> for more info.";

$title_p3[0] 	= "Scholler Study and Activities Expectations";
$rnk_l31[0]	= "develops a complete and intimate familiarity with Fiore dei Liberi's <a href=\"../onlineResources/liberi/liberiHome.htm\"><i>Flos Duellatorum</i></a> and George Silver's <a href=\"../onlineResources/silver/silverHome.htm\">Paradoxes of Defense</a> and <a href=\"../onlineResources/silver/silverHome.htm\">Brief Instructions on my Paradoxes of Defense</a>,";
$rnk_l32[0]	= "schollers are encouraged to practice the drills outside (homework) the formal training session of the Academy,";
$rnk_l33[0]	= "schollers are encouraged to continue with additional <a href=\"trainingCardio.htm\">conditioning</a> and <a href=\"trainingWeights.htm\">strength training</a> to help develop their strength and endurance important for tournament participation,";
$rnk_l34[0]	= "schollers are encouraged to particpate as a representative of the Academy at symposiums, <a href=\"news/wma2000/toronto.html\">workshops</a> and <a href=\"events/dayWithLiberi.htm\">conferences</a>,";
$rnk_l35[0]	= "schollers are expected to participate in the challenges of other scholler candidates for their playing for the prize of a <b>scholler</b> rank,";
$rnk_l36[0]	= "schollers are encouraged to participate in the challenges of other students for the playing for the prize of a <b>scholler</b> rank in other schools upon invitation by that school ( <font color=\"red\"><i><b>Note: </b>if the scholler has not been actively training with any regularity or has been absent from training for three or more months, he/she may not be permitted to physically participate in the freeplay bouts during the scholler test, unless he/she can demonstrate that their fighting skills are current </i></font>),";
$rnk_l37[0]	= "schollers are expected to assist in the general operational and administrative aspects of the Academy (workshop coordination and setup, equipment administration, etc.),";
$rnk_l38[0]	= "schollers are encouraged to purchase authentic period garments if they wish to participate in AEMMA demonstrations and presentations,";
$rnk_l39[0]	= "schollers are encouraged to participate in the governing body of the Academy in an advisory capacity or as part of the executive under invitation,";
$rnk_l310[0]	= "schollers are encouraged to identify a specific project defining an area of study and exploration such as the translation and interpretation of a treatise or <i>fechtbuch</i>, defining a training program for a particular fighting art, e.g. quarterstaff or the <b>scholler</b> can participates and contributes to an existing <a href=\"research_body.htm\" >research &amp; development project</a>, under the direction of another <b>scholler</b> or <b>free scholler</b> or <b>provost</b> or <b>maestro</b>,";
$rnk_l311[0]	= "schollers are expected to provide assistance in training classes when called upon by the instructor or TA.";

$title_p4[0] 	= "Skill Development and Training Specifications for Scholler";
$rnk_l4a[0]	= "<b>Theory</b>";
$rnk_l41[0]	= "develop an intimate familiarity with Fiore dei Liberi's <a href=\"../onlineResources/liberi/liberiHome.htm\"><i>Flos Duellatorum</i></a> across all fighting segments described (armoured and mounted combat optional),";
$rnk_l42[0]	= "develop a complete understanding of combative theory, concepts and history including George Silver's fighting concepts (e.g. true times, false times, governors) as described in <a href=\"../onlineResources/silver/silverHome.htm\">'Brief Instructions on my Paradoxes of Defense'</a>,";
$rnk_l43[0]	= "develop skill, technique and their application to real-time fencing for each training segment concluding with a test at the end of each segment,";
$rnk_l44[0]	= "increased familiarity with the classical Italian nomenclature of guards, strikes, plays, etc.,";
$rnk_l45[0]	= "enhanced understanding and the application of concepts such as hard pressure, soft pressure or kinesthetic awareness into training,";
$rnk_l46[0]	= "enhanced understanding and the application of timing, distance and placement in terms of attack, defense, parry (flat vs edged), reposte,";
$rnk_l47[0]	= "development or contribution to one or more program developments (training programs based on other fighting arts disciplines).";
$rnk_l4b[0]	= "<b>Technical</b>";
$rnk_l51[0]	= "advanced <i>abrazare</i> or grappling techniques,";
$rnk_l52[0]	= "advanced <i>daga</i> (dagger) techniques,";
$rnk_l53[0]	= "advanced <i>spada</i> (arming sword) techniques,";
$rnk_l54[0]	= "<i>spada longa</i> (longsword) techniques,";
$rnk_l55[0]	= "<i>spada e brocchiere</i> (sword & buckler) techniques,";
$rnk_l56[0]	= "<i>azza e lanza</i> (poleaxe & spear) techniques,";
$rnk_l57[0]	= "<i>arme</i> (armoured combat) techniques (optional),";
$rnk_l58[0]	= "exploration and training in other fighting disciplines and a degree of specialization in one or more of the discplines, including but not limited to:";
$rnk_l59[0]	= "German un-armoured longsword,";
$rnk_l510[0]	= "quarter-staff,";
$rnk_l511[0]	= "mounted combat & horsemanship,";
$rnk_l512[0]	= "applying techniques against both single opponents and multi-opponent engagements.";

$title_p6[0] 	= "Other Scholler Attributes:";
$rnk_l61[0]	= "additional drills or plays which may be developed during scholler training by schollers may be introduced into the standard training segment if approved by the AEMMA instructors, provided they are designed to increase the level of experience in the application of defensive and offensive movements, ";
$rnk_l62[0]	= "schollers are encouraged to train in advanced grappling techniques, sword grabbing, half-sword techniques, close-quarters combat, etc. with the possibility of periodic cross-training sessions in JKD to enhance one's sensitivity,";
$rnk_l63[0]	= "estimated scholler training and \"time in\" is at least a 2 - 3 year period before the scholler is able to consider challenging for the prize of free scholler,";
$rnk_l64[0]	= "the training segments of armoured combat and mounted combat are not mandatory for those schollars who wish to pursue the rank of free scholler,";
$rnk_l65[0]	= "schollers must accept the fact that they will inspire recruits to learn and train in the art and therefore, should exhibit a high degree of professionalism and competent fighting skills at all times, in particular, during scholler tests,";
$rnk_l66[0]	= "schollers are encouraged to engage in competitions/tournaments in any fighting style in which the relevant designations were achieved during scholler training.";

$title_p7[0] 	= "Scholler's Heraldic Tradition - Resources:";
$rnk_p71[0]	= "A personal coat of arms is a form of personal identification of which the central element is a shield. Its roots can be found in the early Middle Ages spanning almost 1,000 years of heraldic history, still very much active today.  In general, heraldic achievements (arms) design and symbolism follow traditional channels, but its use can be as modern as the arms of AEMMA displayed on this website. To create a personal coat of arms, or to assume a personal coat of arms, or register or obtain a grant of arms, the following resources will facilitate and educate on the art and science of heraldry.";
$rnk_p72[0]	= "On the subject of assuming of heraldic arms (heraldic achievement), to be clear, it is not illegal to assume arms in Canada, despite the existance of a heraldic authority. Having one's achievement authorized by the <a href=\"http://www.gg.ca/heraldry\" target=\"_blank\">Canadian Heraldic Authority</a> (CHA) means that your arms become the official personal property of you, and becomes a registered entity that can be inherited by your children, if more than one, then differenced to indicate birth order.  The registration of arms with the CHA entitles the heraldic achievement to be included in the official Canadian Archives forever, in particular, the <a href=\"http://reg.gg.ca/heraldry/pub-reg/project.asp?lang=e&ProjectID=402\" target=\"_blank\"><b>Public Register of Arms, Flags and Badges of Canada</b></a>.  Assumed arms do not enjoy the same status, and are more difficult to protect legally if someone should decide to use your arms without your permission. Regardless, schollers are encouraged to have designed personal arms for display during tournaments, and to be suspended for display at the salle d'armes.";

$rnk_row11[0]	= "<a href=\"http://www.heraldry.ca\" target=\"_blank\"><b>Royal Heraldry Society of Canada</b></a> and its Branches mission is to promote the Art and Science of Heraldry, particularly Canadian heraldry, and to encourage an interest in the subject among Canadians. Since the Society's foundation more than three decades ago, the RHSC has never lost sight of its objectives and continues to this day informing and educating Canadians and assisting them and their institutions in the acquisition of properly granted coats of arms. During its first twenty-five years, the Society was the driving force toward the establishment of Canada's own body for the granting of arms. ";
$rnk_row12[0]	= "Members of the Academy who develop a deep interest in the art and science of heraldry, are encouraged to join the Society. The Society has a local Toronto Branch, quite active in heraldry related tours within the GTA, and social functions. Membership fees apply and can be determined by visiting the Society's website at <a href=\"http://www.heraldry.ca\" target=\"_blank\"><b>www.heraldry.ca</b></a> and the Toronto Branch website located at <a href=\"http://toronto.heraldry.ca\" target=\"_blank\"><b>toronto.heraldry.ca</b></a>.";
$rnk_row13[0]	= "Members of the Academy are encouraged to join the RHSC if they are interested in developing their interest and knowledge of heraldry. Membership will provide the opportunity for assistance in the design and development of personal arms.";
$rnk_row21[0]	= "<a href=\"http://www.gg.ca/heraldry\" target=\"_blank\"><b>Canadian Heraldic Authority</b></a> major activities include: granting of new armorial bearings (arms, flags and badges) and native symbols; registration of recognized existing arms, flags and badges; approval of military badges, flags and other insignia of the Canadian Forces; registration of genealogical information related to the inheritance of arms; provision of information on correct heraldic practices; provision of information on heraldic artists who work in various media; and development of, and involvement in, national and regional heraldic ceremonies. These ceremonies, incidentally, may involve the Governor General, who may personally present the new coat of arms and sign the grant document. With few exceptions, only documents the Governor General has personally presented to corporate bodies bear her signature; others are signed by officers of the Canadian Heraldic Authority.";
$rnk_row22[0]	= "For information on the procedure with respect to obtaining an official authorization of personal arms in the form of a grant of arms, click <a href=\"http://www.gg.ca/document.aspx?id=15367&lan=eng\" target=\"_blank\"><b>here</b></a>. To view an example of an authorized grant of personal arms by the Canadian Heraldic Authority of a member of AEMMA, click <a href=\"http://www.heraldry.ca/arms/c/cvet.htm\"><b>here</b></a>.";
$rnk_row31[0]	= "<a href=\"http://www.amateurheralds.org\" target=\"_blank\"><b>International Association of Amateur Heralds</b></a> or the IAAH is a diverse assembly of professional and non-professional genealogists, heraldists, historians, and graphic artists dedicated to providing the general public with heraldic information and design guidance at no charge.  The IAAH stands ready to help you with heraldic research or to design and emblazon a coat of arms you'd like to assume and/or which you've had or which you'd like to have registered with an official heraldic authority. Any armorial bearing the Association helps you design will follow the established rules of heraldry and will be designed free of charge.";
$rnk_row32[0]	= "Members of the Academy are encouraged to utilize the IAAH's service offerings for assistance in the design and development of their personal arms. Membership with the Association is optional and there are <b><font color=\"red\">no membership fees</font></b>.";

$rnk_final[0]	= "<font color=\"#461B7E\"><b>Note:</b> For those schollers who plan on pursuing armoured combat training are encouraged to pursue the acquisition of personal arms (assumed or granted) in order to satisfy further <a href=\"glossary.html#accoutrements\" class=\"linkspurple\">accoutrements</a> for participation in tournaments. Armoured combatants are encouraged to conform to the requirements for arms (shield), banner and jupon/surcoat specified in the <a href=\"medievalTournament.htm#array\" class=\"linkspurple\">Combatant's Array Requirements</a>.</font><br />";

?>
