<?php
// Program: content_mo_about_arms_en.php
//	Description: source for the English textual content on the about the armorial bearings page (mo_about_arms.php)
//	2016 ------------------
//
// English content -------------------
$title[0] = "The Academy's Armorial Bearings (coat of arms)";
$aemma_arms_caption[0] = "The armorial bearings, banner and badge of the Academy of European Medieval Martial Arts.  The grant of arms were sourced from the Canadian Heraldic Authority in Ottawa on January 15, 2008. <sup><a href=\"#1\" title=\"Reference #1: grant of arms\">[1]</a></sup>";
$aemma_arms_evolution_caption[0] = "A depiction of the evolution of the arms of AEMMA from the earliest drawing in 1998 to the current grant of arms.";
$caption_first_arms[0] = "The first rendition of AEMMA's coat of arms, illustrated by David on August 5, 1998. The 'tribal design' on the lower portion of the arms (shield) represents a warrior and which happens to be the same as the tattoo on David's upper right arm.";

$title_p1[0]	= "Symbolism & Heraldry in AEMMA";
$arms_p1_1[0]	= "Symbolism is the use of abstractions to represent and idea or concept. Heraldry is a form of symbolism, which concerns itself with the study, design, regulation and use of armorial bearings, commonly referred to as \"coats of arms\" <sup><a href=\"#2\" title=\"Reference #2: coat of arms\">[2]</a></sup> <sup><a href=\"#3\" title=\"Reference #3: coat of arms (Encyclopædia Britannica)\">[3]</a></sup>. A coat of arms is a form of personal or corporate identification of which the central element is a shield. Its roots began in the early 12th century, largely because of the development at that time of helmets that covered and concealed the face of the wearer. There is a strong connection between heraldry and knights of the period, which were and effective manner of identifying themselves by painting devices (charges or objects) on their shields, to wearing the same symbols on their surcoats worn over armour (hence the \"coat\" in \"coat of arms\") to the caparisons worn by their warhorses. ";
$arms_p1_2[0]	= "Arms (coats of arms) is an important part of the tradition at AEMMA, whereby, students having successfully achieved the rank of Scholar, are encouraged to contemplate their own personal coat of arms.  Assistance in its design and symbolism are provided by a number of members who possess experience in the field of heraldry.  Once the new scholar has completed their design, the arms are then painted on a wooden shield and are then suspended on the wall at the <i>salle d'armes</i>.  The arms suspended are in chronological order from the earliest students (David, Brian, etc.) to the most recent scholars.  The arms are also an important part of the Scholar and Free Scholar tests, as during the portion of the freeplay in the test, the candidate must combat all scholars and above attending the test.  The arms are a reference to all who participate in terms of the order in which they will combat the candidte. The candidate begins the challenges with the newest scholar to free scholars to ultimately, the Provosts of the Academy.";

$title_p2[0]	= "Evolution of AEMMA's Armorial Bearings";
$arms_p2_1[0]	= "From the early sketches of the arms by David in late 1997 to mid-1998, the consistent attributes of the arms included a single sword on the arms (the shield) and two supporting heraldic beasts, originally beginning with dragons. The four rings on the first rendering of the arms represented the first four founding members of \"Version 1.0\" of AEMMA.  These arms continued to evolve whereby in later 1998, the first resemblance of the grant of arms appeared, with the purple chevron and a sword centrally positioned, with point upwards rather than the point downwards as it appeared in the first rendering. Although the chevron and sword made its first appearance in late 1998, the dragon supporters remained. The continued research and training regimine began to stablize on Fiore's works, influencing the evolution of the arms, changing to reflect that new direction of the Academy. This new \"Fioresized\" arms appeared in further renderings earlier in 2000. The heraldic beasts now appear on those arms, sourced from Fiore's <i>sette spada</i> folio.  The basic tinctures and charges on the arms stabilized with the chevron purpure on a shield Argent with sword proper pointing upwards. Later in 2002, the arms take on a closure rendering to the official grant of arms from 2007 and proclaimed on January 15, 2008. These arms preserved the heraldic beasts from Fiore, changed the presentation of the motto and banner and the mound on which the supporters and arms stand. The arms are also visible on Canada's <a href=\"http://reg.gg.ca/heraldry/pub-reg/project.asp?lang=e&ProjectID=1209\" target=\"_blank\" title=\"Public Register of Arms, Flags and Badges of Canada\">Public Register of Arms, Flags and Badges of Canada</a>  <sup><a href=\"#4\" title=\"Reference #4: Public Register of Arms, Flags and Badges of Canada\">[4]</a></sup>.";

$title_p3[0]	= "Symbolism of AEMMA's Armorial Bearings";
$arms_p3_1[0]	= "The Canadian Heraldic Authority archives not only the grant of arms, but the symbolism which describe and explain the design and the charges on the arms. The official symbolism for the AEMMA arms are as follows:<ul><li><b>Arms: </b>The sword represents the medieval martial arts which the Academy is dedicated to studying.</li><li><b>Crest: </b>The lynx represents one of the four attributes of the ancient fighting art outlined in the treatise Flos Duellatorum by Fiore dei Liberi (c.1410), specifically \"prudentia\", meaning prudence or caution. The lynx is known for its keen eyesight, and the dividers it holds indicate the importance of precise measurements in combat. The dagger is one of the weapons used in medieval fighting.</li><li><b>Supporters: </b>The supporters represent two other attributes from the dei Liberi work. The lion represents “audatia”, or courage, and is shown with a heart, which also represents courage in the manuscript. The heraldic “tyger” represents “celeritas” or swiftness. It is shown with an arrow, as tigers were reputed to be able to snatch an arrow in mid-flight. The halberd and spear are other weapons used in medieval combat. The compartment contains floral symbols of Canada and Ontario. The fourth attribute from the dei Liberi work, “fortitudo”, or strength, represented by an elephant, not shown here.</li><li><b>Motto :</b>These four words are the attributes named in the de Liberi treatise, and mean \"Prudence, daring, swiftness, and strength.\"</li><li><b>Flag :</b>The symbolism of this emblem is found in other element(s) of this record.</li><li><b>Badge :</b>The badge incorporates symbols to emphasize various abilities necessary for successful fighters: the tower, to remain upright and strong; the dividers, to assess a situation correctly; the arrow, to act swiftly; and the heart, to fight with necessary intensity, confidence and courage.</li></ul>";

$arms_l1[0]	= "<a href=\"http://www.gg.ca/document.aspx?id=2&lan=eng\" target=\"_blank\" title=\"The Canadian Heraldic Authority\">The Canadian Heraldic Authority</a> (CHA; French: <a href=\"http://www.gg.ca/document.aspx?id=2&lan=fra\" target=\"_blank\" title=\"L'Autorité héraldique du Canada\"><i>L'Autorité héraldique du Canada</i></a>) is part of the Canadian honours system under the Canadian monarch, whose authority is exercised by the Governor General of Canada. The authority is responsible for the creation and granting of new coats of arms (armorial bearings), flags, and badges for Canadian citizens and corporate bodies. The authority also registers existing armorial bearings granted by other recognized heraldic authorities, approves military badges, flags, and other insignia of the Canadian Forces, and provides information on heraldic practices.  The <a href=\"http://www.heraldry.ca\" target=\"_blank\" title=\"Royal Heraldry Society of Canada\">Royal Heraldry Society of Canada</a> was instrumental in the formation of the Canadian Heraldic Authority, which was established on June 4, 1988. Last accessed: April 21, 2016.";
$arms_l2[0]	= "A coat of arms is a unique heraldic design on an escutcheon (i.e. shield), surcoat, or tabard. The coat of arms on an escutcheon forms the central element of the full heraldic achievement which consists of shield, supporters, crest, and motto. The design is a symbol unique to an individual person or family (except in the UK), corporation, or state. source: Wikipedia. <a href=\"=https://en.wikipedia.org/wiki/Coat_of_arms\" target=\"_blank\">Coat of arms</a>. Last accessed: January 17, 2017.";
$arms_l3[0]	= "Coat of arms, the principal part of a system of hereditary symbols dating back to early medieval Europe, used primarily to establish identity in battle. Arms evolved to denote family descent, adoption, alliance, property ownership, and, eventually, profession. source: Encyclopædia Britannica. <a href=\"=https://www.britannica.com/topic/coat-of-arms\" target=\"_blank\">Coat of arms - Heraldry</a>. Last accessed: January 17, 2017.";
$arms_l4[0]	= "The Public Register of Arms, Flags and Badges of Canada contains the heraldic emblems that have been granted, registered, approved or confirmed by the Canadian Heraldic Authority since its inception on June 4, 1988. In 2005, the Canadian Heraldic Authority began the process of creating a digital version of the register available online.";
?>
