<?php
// Program: content_mo_trng_intro_armizare_en.php
//	Description: source for the English textual content on the new to this page (mo_trng_intro_armizare.php)
//	2017 ------------------
//	jan 15:	introductory course fee is set in config.php, a single variable to ease on maintenance
//	jun 28:	PHP config variables $intro_armizare_start_time[0] and $intro_armizare_end_time[0] were added to the central config.php (fee there too)
//
// English content -------------------
if (isset($_GET['MNU'])) { $title[0] = "Introduction Course on l`arte dell`armizare (Armizare)"; } else { $title[0] = "New to this?  Start with an intro course on Armizare";}
$new_red[0] = "new.png";
$new_1_p1[0]	= "The <b>Academy of European Medieval Martial Arts</b> or <b>AEMMA</b> has conducted research and development, training and instruction in historical European martial arts (HEMA) <sup><a href=\"#1\" title=\"Reference #1: HEMA\">[1]</a></sup> <sup><a href=\"#2\" title=\"Reference #2: HEMAC\">[2]</a></sup> since 1998 and is Canada's longest running HEMA Academy. AEMMA has never waivered from its mission, and will continue to evolve, develop, train and instruct HEMA providing to students, authentic martial arts training and unique fitness and training environment unparalleled in Canada.  Located in downtown Toronto in the Annex at the corner of Dupont and Ossington is easily reached via TTC, car, cycling or walking. ";
$new_1_p2[0]	= "If you are new to the world of HEMA, and are interested in pursuing training in the ancient art, the introduction program to <i>Armizare</i> is an outstanding way to determine whether or not, HEMA is for you while incurring minimal expense in training fees and equipment. You will learn in the program information on the history of <i>Armizare</i>, Maestro Fiore dei Liberi (the swordsmaster who had authored the treatises on the fighting art), sources of study and materials, and fundamentals on abraçare (grappling), daga (dagger) and spada (sword). Students successfully completing the introductory course qualifies him/her to join the Academy and enroll in the regular training program in the rank of recruit, the first rank in long-term training in <i>Armizare</i>. ";

$title_2[0] = "Equipment Requirements for the Introduction to l'arte dell'armizare (Armizare)";
$new_2_p1[0] = "The following list is the minimum training equipment required for any individual interested in starting with the intro training program:";
$new_2_l1[0] = "a comfortable t-shirt/training shirt (AEMMA training t-shirts are available @ $20, and may have some in stock at the salle d'armes for purchase),";
$new_2_l2[0] = "comfortable leggings/sweats/shorts (summer only),";
$new_2_l3[0] = "running shoes or flat-soled wrestling/boxing boots,";
$new_2_l4[0] = "pair of leather garden gloves or similar.";
$new_2_p2[0] = "Weapons are provided (daggers, swords). Clearly, the equipment requirements will require little or no investment should you already have the items mentioned.";

$title_3[0] = "Schedule and Fee";
$new_3_p1[0] = "<b>Schedule: </b>The introductory program are scheduled every two months, and begin the first Monday of that month and are scheduled twice weekly for four (4) weeks on <b>Monday and Wednesday evenings, ".$intro_armizare_start_time[0]." - ".$intro_armizare_end_time[0].".</b>  The intro programs are scheduled for starting in January, March, May, July, September and November.</p><p><b>Fee:</b> <b style='color:green;'>$".$intro_fee."</b> (all in).  The fee is payable via Paypal to the Academy (via the Fighting Arts Collective Toronto <sup><a href=\"#3\" title=\"Reference #3: FACT\">[3]</a></sup>) by clicking on the Paypal button.  Paypal will accept debit/credit cards via a secured Paypal transaction.";
$new_3_p2[0] = "After you have submitted a payment to the Academy using the Paypal method, click here to send an email to the Academy confirming you've made your payment, and provide your full name, address, telephone, email and the month you wish to begin your introductory training.  You will get contacted by the Academy by email/phone to confirm receipt and your registration into the program.";

$new_3_l1[0]	= "Historical European martial arts (HEMA) refers to martial arts of European origin, particularly using arts formerly practised, but having since died out or evolved into very different forms. The term Western martial arts (WMA) is sometimes used in the United States and in a wider sense including modern and traditional disciplines. During the Late Middle Ages, the longsword had a position of honour among these disciplines, and sometimes historical European swordsmanship (HES) is used to refer to swordsmanship techniques specifically. source: Wikipedia. <a href=\"https://en.wikipedia.org/wiki/Historical_European_martial_arts\" target=\"_blank\">Historical European martial arts</a>. Retrieved: January 17, 2017.";
$new_3_l2[0]	= "The Historical European Martial Arts Coalition (HEMAC) is a collection of martial artists and researchers in Europe.  They are dedicated to the study, reconstruction, practice and promotion of traditional European fighting arts, based on the study of surviving technical sources (treatises and manuals). HEMAC was established in 2001 and is a non-hierarchical, round-table organisation, consisting of individual researchers and martial artists from many groups across Europe. source: <a href=\"http://www.hemac.org/\" target=\"_blank\" title=\"HEMAC\">HEMAC</a>. Retrieved: January 17, 2017.";
$new_3_l3[0]	= "Fighting Arts Collective is the premier combative martial arts school in Toronto specializing in real world solutions, historical context and unconventional fitness programs. Founded in 2004 by world-class instructors, FACT is committed to upholding the values of collaboration, healthy living and the pursuit of warriorship. They currently have 9 schools teaching 8 martial arts, weapons skills, several fitness programs and an aerial school. They also host workshops, events and seminars with local and international instructors. source: <a href=\"http://www.fightingartscollective.com\" target=\"_blank\">Fighting Arts Collective Toronto</a>. Retrieved: January 17, 2017.";

?>
