<?php
// Program: AIMS_sub_show_username_profile_en.php
//	Description: source for the English textual content on the subroutine for presenting detailed membership records (sub_show_username_profile.php)
//	2016 ------------------
//
// English content -------------------
$note_non_dba[0] = "<b>Note: </b>Your access privileges enable you to view a record, however, your access level prevents you from updating any records. If an error is noticed, please click on <b>EMAIL HELP</b> below left<br />&nbsp;to inform the database administrator of the error.";
$note_member[0] = "<b>Note: </b>Your access privileges as <b>member</b> does not permit you to view any record within AIMS. Please logoff from AIMS and return to the members only area. Your access attempt has been logged.";
$note_dba[0] = "<b>Note: </b>Your access privileges as <b>database administrator (DBA)</b> or <b>administrator</b> enable you to enter a new record of any level or rank and/or update any record.";
$title_password[0] = "The password appears encrypted and are encrypted by the system prior to being saved to the AIMS database.  The encrypted password CANNOT be decrypted. When you enter a new password or change an existing password, it will appear as normal English on this window.";
$title_creation_date[0] = "This field cannot be edited.  The creation date is generated by the system at the time when the username was created.";
$title_non_disclosure[0] = "The non-disclosure is only necessary when the member requires access to the AIMS system. Regular members do not need to have a non-disclosure signed nor checked on this window. This would only be assigned by AEMMA's Administrator.";
$title_non_disclosure_download[0] = "Click to peruse/download AEMMA&apos;s Non-disclosure form.";
?>
