<?php
 session_save_path("/home/users/web/b2211/nf.aemma/cgi-bin/tmp");
	session_start();
	include_once 'library_IDValid.php';
	include_once 'library_DB.php';
?>
<html>
<head>
	<link rel="stylesheet" href="css/default.css" type="text/css">
	<script type="text/javascript" src="library_main_expired.js"></script>
</head>
<body bgcolor="white">
<center><table cellpadding="0" cellspacing="0" width="800" bgcolor="white">
<?php
	$full_date= date("d-m-Y");	
	$year = date("Y");
	$month = date("m");
	$day = date("d");
	$todays_date = $year."-".$month."-".$day;
	$count = 0;
//	echo ('debug: year = '.$year.', month = '.$month.', expiry date ='.$expiry_date);
//	echo ('todays date = '.$todays_date);
	echo ('<caption>Expired Online Library Registrations as of Today ('.$full_date.')</caption>');
	echo ('<tr><th>Name</th><th>Country</th><th>Email</th><th>Registration Date</th><th>Last Access Date</th><th>Renewal Notice</th><th>Counter&nbsp;</th></tr>');

	$LinkID=dbConnect($DB);
	$SQL = 'SELECT R.ID, R.userID, R.first_name, R.middle_initial, R.surname, R.country, R.email, R.registration_date, R.privileged, R.last_access_date, R.renewal_notice, R.access_counter';
	$SQL .= ' FROM registeredUsers R';
	$SQL .= ' WHERE R.access_status = 1 and R.privileged = 0 and R.member_status = 0 ';
	$SQL .= ' ORDER BY R.registration_date DESC';

	$Result = mysql_query($SQL, $LinkID);
	while ($Line = mysql_fetch_object($Result)) 
		{

		// determine the record's expiration date and compare to today's date ( syntax: yyyy-mm-dd )
		$reg_date = $Line->registration_date;
		$reg_year = substr($reg_date,0,4);
		$reg_month = substr($reg_date,5,2);
		$reg_day = substr($reg_date,-2);
		$exp_year = $reg_year + 1;
		$exp_date = $exp_year."-".$reg_month."-".$reg_day;
//		echo ('debug: exp date = '.$exp_date);

		if ( $exp_date < $todays_date )
			{
			$count = $count + 1;
			
			$renewal_notice = $Line->renewal_notice;
			$font_start = "";
			$font_end = "";

			$last_access_date = $Line->last_access_date;
			$last_access_date = substr($last_access_date,0,10);

			if ($renewal_notice == 1)
				{ 
				$font_start = '<font color="green">';
				$font_end = '</font>';
				}

			echo ('<tr OnMouseOver="navBar(this,1,1);"');
			echo (' OnMouseOut="navBar(this,2,1);"');
			echo (' OnClick="navBarClick(this,1,\'' . $Line->ID . '\')">');

			echo ('<td><div id="Data">'.$font_start . $Line->surname . ', ' . $Line->first_name .' ' . $Line->middle_initial . $font_end.'</div></td>');
			echo ('<td><div id="Data">'.$font_start . $Line->country . $font_end.'</div></td>');
			echo ('<td><div id="Data" align="left">'.$font_start . $Line->email . $font_end.'</div></td>');
			echo ('<td><div id="Data" align="center">'.$font_start . $Line->registration_date . $font_end.'</div></td>');
			echo ('<td><div id="Data" align="center">'.$font_start . $last_access_date . $font_end.'</div></td>');
			echo ('<td><div id="Data" align="center">'.$font_start . $Line->renewal_notice . $font_end.'</div></td>');
			echo ('<td><div id="Data" align="center">'.$font_start . $Line->access_counter . $font_end.'</div></td>');
			echo ('</tr>');
			}
		}
	echo ('<tr bgcolor="gray"><td colspan="7"><font face="arial,helvetica,sans-serif" size="-2" color="white">&nbsp;<b>Total number of <b>expired</b> registrations: </b>'.$count.'&nbsp;&nbsp;</td></tr>');
	echo ('</ul></div>');
	mysql_free_result($Result);
	dbClose($LinkID);
?>
<tr>
	<td colspan="7">&nbsp;<br /></td>
</tr>
<tr>
	<td colspan="7"><font face="arial,helvetica,sans-serif" size="-1"><b>Note: </b>Expired members are those individuals whose access status is "1" and who are NOT AEMMA members (i.e. privileged members nor member status), and whose access has expired, i.e. it's past one year since their registration date.
	<p>Records which are highlighted in <font color="green"><b>green</b></font> have been sent email renewal notices generated by library_Members.php when renewal notice set to "1", and the date sent logged in Evo. These should have their "access status" set to "0" on the next "cycle" of expiry report as set by Evo.</p> </td>
</tr>
</table></center>
<br /><p><center><form action="0"><input type="button" value="Print This Report" onClick="window.print()" name="button"></form></center></p>
</body>
</html>
