<?php
// Program: Tab_personal_profile.php
// Author: David M. Cvet
// Created: Nov 04, 2016
// Description:
//	This will display the detailed student's record on an online form including portrait, address, notes. This pgm is called by Members_show.php.
//---------------------------
// Updates:
//	2016 -------------------
//	oct 12:	TO DO!!!!!!!!!!!  When the "cancel new record entry" button is clicked, the new blank record in tbl_Members MUST BE DELETED (house-keeping)
//	2018 -------------------
//	apr 25:	consolidated conditionals for state when "Update" or other reducing the number of if...else... statements.
//	2019 -------------------
//	jan 26:	adjusted field widths to present properly in Windows without truncating the visible data
//
include "config/AIMS_sub_show_personal_profile_$lang.php";

// setup main div object for presenting personal information profile record
if ($state == "Update")
	{
	if ($pref_name)
		{$name_in_title_bar = $pref_name."'s";}
	else
		{$name_in_title_bar = $first_name."'s";}
	echo ("\n\t".'<form name="Personal_Profile_Form" method="post" action="sub_update_personal_profile.php">');
	$remaining_title = "Member Number# ".$member_number."</b>";
	}
else
	{
	$name_in_title_bar = "new";
	echo ("\n\t".'<form name="Personal_Profile_Form" method="post" action="sub_create_personal_profile.php">');
	$remaining_title = "Member Number# ( <i>not yet assigned</i> )</b>)";
	}

//echo ('debug:sub_show_personal_profile:10:member_ID="'.$member_ID.'"');//exit;
echo ('<div class="personal_profile_main box">');
// setup the member's personal profile header (the green title bar)
echo ("\n\t".'<div style="float:left;width:100%;height:24px;text-align:center;margin:auto;padding-top:3px;" class="bggreen"><img src="../images/icons/user.gif" alt="" style="margin-right:5px;vertical-align:middle;height:20px;" />&nbsp;<b>'.$name_in_title_bar.' Personal Profile&nbsp;&mdash;&nbsp;'.$remaining_title.'</div>'."\n");
	// check security level and determine access level and insert a new div to inform the user, note to cross all three columns
if ($_SESSION["RoleID"] < 5 && $_SESSION["RoleID"] > 1) // this is a non-dba/admin level of access, read access only
	{ echo ('<div style="float:left;width:100%;height:24px;text-align:center;margin:auto;border-style:groove;padding-top:3px;background-color:#fdd017">'.$note_non_dba[$lang_num].'</div>'); }
elseif ($_SESSION["RoleID"] == 1)
	{ echo ('<div style="float:left;width:100%;height:24px;text-align:center;margin:auto;border-style:groove;padding-top:3px;background-color:#fdd017">'.$note_member[$lang_num].'</div>'); }
if ($state == "Create" && $_SESSION["RoleID"] >= 5) //this is a user who can read and insert new records of any kind
	{ echo ('<div style="float:left;width:100%;height:24px;text-align:center;margin:auto;border-style:groove;padding-top:3px;background-color:#fdd017">'.$note_dba[$lang_num].'</div>'); }

	// left record column div
echo ('<div class="pers_profile_col1"><!-- begin left record column -->');
echo ("\n\t".'<table border="0" align="center" style="width:100%;" cellpadding="0" cellspacing="2">');
if ($state == "Create" && $_SESSION["RoleID"] >= 5) //this is a user who can read and insert new postulant records
	{ $color = "#b8b7b7"; }
else { $color= "#333333"; }
echo ("\n\t".'<tr>'."\n\t\t".'<td colspan="2" style="font-size:16px;width:18%;background-color:orange;border-style:dotted;border-width:1px;padding-left:4px;">&nbsp;&nbsp;<img src="images/icons/note.gif" style="vertical-align:middle;width:20px;margin-right:4px;cursor:help;" alt="" title="Member ID is automatically generated by the AIMS system. It guarrantees that a unique identifier is assigned to member\'s records." /><span class="Label">Member ID:</span> ');
// $member_ID is generated within Members_show.php for when state = "Create" 
// this blank record must be deleted should the create process be cancelled or incomplete
echo ('&nbsp;<input type="text" name="MemID" maxlength="8" style="width:15%;" value="'.$member_ID.'" readonly="readonly" /><br />');
if ($state == "Create")
	{
	echo ('<input type="hidden" name="AdminID" value="'.$admin_ID.'"/ ><i><b>Admin use only:</b> a unique member ID will be auto-generated by AIMS after the new member\'s record has been saved to the database.</i><br /><img src="images/icons/hand_right_pointing.gif" alt="" style="vertical-align:middle;" />&nbsp;new record to be created by: <font color="green"><b>'.$admin_ID.'</b></font><br /><img src="images/icons/hand_right_pointing.gif" alt="" style="vertical-align:middle;" />&nbsp;on: <font color="green"><b>'.$record_creation_date.'</b></font></td>'."\n\t".'</tr>');
	}
else
	{
	echo ('<i>Admin use only: member ID is auto-generated by AIMS<br />record created by: <b>'.$admin_ID.'</b>, record created on: <b>'.$record_creation_date.'</b></i></td>'."\n\t".'</tr>');
	}
echo ('	<tr>');
echo ('		<td style="width:30%;" class="Label">Member Num#</td>');
echo ('		<td style="width:70%;"><input type="text" name="MemNumber" id="MemNumber" maxlength="8" style="width:22%;" value="'.$member_number.'" tabindex="1" autofocus oninput="enable_submit_personal_button()" />&nbsp;<img src="images/icons/note.gif" style="vertical-align:middle;width:20px;margin-right:4px;cursor:help;" alt="" title="Member Number is created by the administrator manually using a standard formula. If a member number is not entered when creating a new record, it will be assigned the auto-generated Member ID. This can be changed later if necessary." /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Salutation:</td>
		<td style="width:70%;"><input type="text" name="Salutation" maxlength="32" style="width:22%;" value="'.$salutation.'" tabindex="2" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Surname:</td>
		<td style="width:70%;"><input type="text" name="LName" maxlength="48" style="width:60%;" value="'.$last_name.'" tabindex="3" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">First Name:</td>
		<td style="width:70%;"><input type="text" name="FName" maxlength="48" style="width:60%;" value="'.$first_name.'" tabindex="4" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Middle Name:</td>
		<td style="width:70%;"><input type="text" name="MName"  maxlength="48" style="width:60%;" value="'.$middle_name.'" tabindex="5" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('<tr>
		<td style="width:30%;" class="Label">Preferred Name:</td>
		<td style="width:70%;"><input type="text" name="PName"  maxlength="48" style="width:60%;" value="'.$pref_name.'" tabindex="6" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Post Nominal(s):</td>
		<td style="width:70%;"><input type="text" name="Postnominals"  maxlength="36" style="width:65%;" value="'.$postnominals.'" tabindex="7" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Birth Date:</td>
		<td style="width:70%;"><input type="text" name="BirthDate" id="BirthDate" data-zdp_first_day_of_week="0" maxlength="10" size="9" placeholder="yyyy-mm-dd" value="'.$birth_date.'" tabindex="8" onclick="enable_submit_personal_button()" /> <img src="../images/icons/event_icon.gif" alt="" style="vertical-align:middle" />
				<script type="text/javascript">$(\'#BirthDate\').Zebra_DatePicker();</script></td>
	</tr>');

//echo ('	<tr>
//		<td style="width:30%;" class="Label">Year of Birth:</td>
//		<td style="width:70%;"><input type="text" name="YearOfBirth" maxlength="4" size="1" value="'.$year_of_birth.'" tabindex="9" oninput="enable_submit_personal_button()" style="cursor:pointer;" title="The year is automatically calculated should the birth date been entered and has been saved to the system" /></td>
//	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Gender:</td>');
		if ($state == "Create")
			{
			echo ('<td style="width:70%;text-align:left;" class="Label">&nbsp;male: <input type="radio" name="Sex" value="M"  CHECKED  style="vertical-align:middle" tabindex="10" />&nbsp;&nbsp;&nbsp;female: <input type="radio" name="Sex" value="F" style="vertical-align:middle" tabindex="11" /></td>');
			}
		else
			{
			echo ('<td style="width:70%;text-align:left;" class="Label">&nbsp;male: <input type="radio" name="Sex" value="M" '. ($gender == 'M' ? 'CHECKED' : '') .'  style="vertical-align:middle" tabindex="10" oninput="enable_submit_personal_button()" />&nbsp;&nbsp;&nbsp;female: <input type="radio" name="Sex" value="F" '. ($gender == 'F' ? 'CHECKED' : '') .' style="vertical-align:middle" tabindex="11" oninput="enable_submit_personal_button()" /></td>');
			}
echo ('	</tr>');
//echo ('	<tr>
//		<td style="width:30%;" class="Label">Language:</td>');
//		if ($state == "Create")
//			{
//			echo ('<td style="width:70%;" class="Label">English: <input type="radio" name="Language" value="0"  CHECKED  style="vertical-align:middle" tabindex="12" />&nbsp;&nbsp;&nbsp;French: <input type="radio" name="Language" value="1" style="vertical-align:middle" tabindex="13" /></td>');
//			}
//		else
//			{
//			echo ('<td style="width:70%;" class="Label">English: <input type="radio" name="Language" value="0" '. ($language == '0' ? 'CHECKED' : '') .'  style="vertical-align:middle" tabindex="12" />&nbsp;&nbsp;&nbsp;French: <input type="radio" name="Language" value="1" '. ($language == '1' ? 'CHECKED' : '') .' style="vertical-align:middle" tabindex="13" /></td>');
//			}
//echo ('	</tr>');
//echo ('	<tr>
//		<td style="width:30%;" class="Label">Date Joined:</td>
//		<td style="width:70%;"><input type="text" name="DateJoined" id="DateJoined" data-zdp_first_day_of_week="0"  maxlength="10" size="6" placeholder="yyyy-mm-dd" value="'.$date_joined.'" tabindex="8" onclick="enable_submit_personal_button()" /> <img src="../images/icons/event_icon.gif" alt="" style="vertical-align:middle" />
//				<script type="text/javascript">$(\'#DateJoined\').Zebra_DatePicker();</script></td>
//	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Occupation:</td>
		<td style="width:70%;"><input type="text" name="Occupation"  maxlength="48" style="width:80%;" value="'.$occupation.'" tabindex="14" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Spouse:</td>
		<td style="width:70%;"><input type="text" name="Spouse"  maxlength="128" style="width:60%;" value="'.$spouse.'" tabindex="16" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Emerg Contact:</td>
		<td style="width:70%;"><input type="text" name="EmergContactName"  maxlength="64" style="width:60%;" value="'.$emerg_contact.'" tabindex="15" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Emerg Contact Phone:</td>
		<td style="width:70%;"><input type="text" name="EmergContactPhone"  maxlength="14" style="width:35%;" value="'.$emerg_contact_phone.'" tabindex="15" oninput="enable_submit_personal_button()" /></td>
	</tr>');

//echo ('	<tr>
//		<td style="width:30%;" class="Label">Wedding Anniv.:</td>
//		<td style="width:70%;"><input type="text" name="WeddingAnniv" data-zdp_first_day_of_week="0"  maxlength="10" size="6" placeholder="yyyy-mm-dd" value="'.$wed_anniv_date.'" tabindex="17" id="WeddingAnniv" onclick="enable_submit_personal_button()" /> <img src="../images/icons/event_icon.gif" alt="" style="vertical-align:middle" />
//				<script type="text/javascript">$(\'#WeddingAnniv\').Zebra_DatePicker();</script> yyyy-mm-dd</td>
//	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Deceased:</td>
		<td style="width:70%;"><input type="checkbox" name="DeceasedCheck" value="1" '. ($deceased == 1 ? 'CHECKED' : '') .'  style="vertical-align:middle" oninput="enable_deceased_date()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Deceased Date:</td>
		<td style="width:70%;"><input type="text" name="DeceasedDateForm" id="DeceasedDateForm" data-zdp_first_day_of_week="0"  maxlength="10" size="9" placeholder="yyyy-mm-dd" value="'.$deceased_date.'" disabled="true" onclick="enable_submit_personal_button()" /> <img src="../images/icons/event_icon.gif" alt="" style="vertical-align:middle" />
				<script type="text/javascript">$(\'#DeceasedDateForm\').Zebra_DatePicker();</script> yyyy-mm-dd</td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Heard From:</td>
		<td style="width:70%;"><input type="text" name="HeardFrom" maxlength="32" style="width:60%;" value="'.$heard_from.'" tabindex="41" oninput="enable_submit_personal_button()" /></td>
	</tr>');

echo ('</table>');
echo ("\n".'</div><!-- end left record column "pers_profile_col1" -->');
	// middle record column div

echo ("\n".'<div class="pers_profile_col2"><!-- begin middle record column -->');
echo ("\n\t".'<table border="0" align="center" width="100%" cellpadding="0" cellspacing="2">');
//echo ('	<tr>
//		<td colspan="2">&nbsp;</td></tr><tr>
//		<td style="width:30%;" class="Label">Nominated by:</td>
//		<td style="width:70%;"><input type="text" name="NominatedBy" maxlength="512" size="18" value="'.$nominated_by.'" tabindex="17" oninput="enable_submit_personal_button()" /></td>
//	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Home:</td>
		<td style="width:70%;"><input type="text" name="NumHome" maxlength="14" style="width:35%;" value="'.$num_home.'" tabindex="18" placeholder="(123) 456-7890" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Business:</td>
		<td style="width:70%;"><input type="text" name="NumWork" maxlength="14" style="width:35%;" value="'.$num_work.'" tabindex="19" placeholder="(123) 456-7890" oninput="enable_submit_personal_button()" /> <span class="Label">Ext#<input type="text" name="NumWorkExt" maxlength="4" size="1" value="'.$num_work_ext.'" tabindex="20" /></span></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Fax:</td>
		<td style="width:70%;"><input type="text" name="NumFax" maxlength="14" style="width:35%;" value="'.$num_fax.'" tabindex="21" placeholder="(123) 456-7890" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Mobile:</td>
		<td style="width:70%;"><input type="text" name="NumMobile" maxlength="14" style="width:35%;" value="'.$num_mobile.'" tabindex="22" placeholder="(123) 456-7890" oninput="enable_submit_personal_button()" /></td>
	</tr>');
//echo ('	<tr>
//		<td style="width:30%;" class="Label">Other:</td>
//		<td style="width:70%;"><input type="text" name="NumOther" maxlength="14" size="6" value="'.$num_other.'" tabindex="23" placeholder="(123) 456-7890" oninput="enable_submit_personal_button()" /></td>
//	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Email:</td>
		<td style="width:70%;"><input type="text" name="Email" maxlength="96" style="width:75%;" value="'.$email.'" tabindex="24" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Email (alt):</td>
		<td style="width:70%;"><input type="text" name="EmailAlt" maxlength="96" style="width:75%;" value="'.$email_alt.'" tabindex="25" oninput="enable_submit_personal_button()" /></td>
	</tr>');
//echo ('	<tr>
//		<td class="Label">Preferred Mailing Address:</td>
//		<td style="width:70%;">&nbsp;&nbsp;<font color="green">Address</font>:<input type="radio" name="MailingAddress" value="0" '. ($mailing_address == '0' ? 'CHECKED' : '') .'  style="vertical-align:middle" tabindex="26" />&nbsp;&nbsp;<font color="red">Address (Alt)</font>:<input type="radio" name="MailingAddress" value="1" '. ($mailing_address == '1' ? 'CHECKED' : '') .' style="vertical-align:middle" tabindex="27" /></td>
//	</tr></table>');
//echo ('</table>');
//echo ("\n\t".'<table align="center" width="100%" cellpadding="0" cellspacing="2" style="border:2px solid green;border-radius:5px;">');
echo ("\n\t".'<tr>
		<td style="width:30%;" class="Label">Address:</td>
		<td style="width:70%;"><textarea name="Address" rows="3" cols="26" wrap="virtual" tabindex="28" oninput="enable_submit_personal_button()">'.$address.'</textarea></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">City:</td>
		<td style="width:70%;"><input type="text" name="City" maxlength="32" style="width:65%;" value="'.$city.'" tabindex="29" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td colspan="2"><span class="Label">Province:</span> <select name="ProvState" tabindex="30" style="cursor:pointer" oninput="enable_submit_personal_button()">
					<option value="">&nbsp;</option>
					<option value="AB" '.($prov_state == "AB" ? 'SELECTED' : '').' title="Alberta">AB&nbsp;</option>
					<option value="BC" '.($prov_state == "BC" ? 'SELECTED' : '').' title="British Columbia">BC&nbsp;</option>
					<option value="MB" '.($prov_state == "MB" ? 'SELECTED' : '').' title="Manitoba">MB&nbsp;</option>
					<option value="NB" '.($prov_state == "NB" ? 'SELECTED' : '').' title="New Brunswick">NB&nbsp;</option>
					<option value="NL" '.($prov_state == "NL" ? 'SELECTED' : '').' title="Newfoundland and Labrador">NL&nbsp;</option>
					<option value="NT" '.($prov_state == "NT" ? 'SELECTED' : '').' title="Northwest Territory">NT&nbsp;</option>
					<option value="NS" '.($prov_state == "NS" ? 'SELECTED' : '').' title="Nova Scotia">NS&nbsp;</option>
					<option value="NU" '.($prov_state == "NU" ? 'SELECTED' : '').' title="Nunavut">NU&nbsp;</option>
					<option value="ON" '.($prov_state == "ON" ? 'SELECTED' : '').' title="Ontario">ON&nbsp;</option>
					<option value="PE" '.($prov_state == "PE" ? 'SELECTED' : '').' title="Prince Edward Island">PE&nbsp;</option>
					<option value="QC" '.($prov_state == "QC" ? 'SELECTED' : '').' title="Quebec">QC&nbsp;</option>
					<option value="SK" '.($prov_state == "SK" ? 'SELECTED' : '').' title="Saskatchewan">SK&nbsp;</option>
					<option value="YT" '.($prov_state == "YT" ? 'SELECTED' : '').' title="Yukon Territory">YT&nbsp;</option>
					<option value="" >--</option>
					<option value="AL" '.($prov_state == "AL" ? 'SELECTED' : '').' title="Alabama">AL&nbsp;&nbsp;</option>
					<option value="AK" '.($prov_state == "AK" ? 'SELECTED' : '').' title="Alaska">AK&nbsp;&nbsp;</option>
					<option value="AZ" '.($prov_state == "AZ" ? 'SELECTED' : '').' title="Arizona">AZ&nbsp;&nbsp;</option>
					<option value="AR" '.($prov_state == "AR" ? 'SELECTED' : '').' title="Arkansas">AR&nbsp;&nbsp;</option>
					<option value="CA" '.($prov_state == "CA" ? 'SELECTED' : '').' title="Califorina">CA&nbsp;&nbsp;</option>
					<option value="CO" '.($prov_state == "CO" ? 'SELECTED' : '').' title="Colorado">CO&nbsp;&nbsp;</option>
					<option value="CT" '.($prov_state == "CT" ? 'SELECTED' : '').' title="Connecticut">CT&nbsp;&nbsp;</option>
					<option value="DE" '.($prov_state == "DE" ? 'SELECTED' : '').' title="Delaware">DE&nbsp;&nbsp;</option>
					<option value="FL" '.($prov_state == "FL" ? 'SELECTED' : '').' title="Florida">FL&nbsp;&nbsp;</option>
					<option value="GA" '.($prov_state == "GA" ? 'SELECTED' : '').' title="Georgia">GA&nbsp;&nbsp;</option>
					<option value="HI" '.($prov_state == "HI" ? 'SELECTED' : '').' title="Hawaii">HI&nbsp;&nbsp;</option>
					<option value="ID" '.($prov_state == "ID" ? 'SELECTED' : '').' title="Idaho">ID&nbsp;&nbsp;</option>
					<option value="IL" '.($prov_state == "IL" ? 'SELECTED' : '').' title="Illinois">IL&nbsp;&nbsp;</option>
					<option value="IN" '.($prov_state == "IA" ? 'SELECTED' : '').' title="Iindiana">IN&nbsp;&nbsp;</option>
					<option value="IA" '.($prov_state == "IA" ? 'SELECTED' : '').' title="Iowa">IA&nbsp;&nbsp;</option>
					<option value="KS" '.($prov_state == "KS" ? 'SELECTED' : '').' title="Kansas">KS&nbsp;&nbsp;</option>
					<option value="KY" '.($prov_state == "KY" ? 'SELECTED' : '').' title="Kentucky">KY&nbsp;&nbsp;</option>
					<option value="LA" '.($prov_state == "LA" ? 'SELECTED' : '').' title="Louisiana">LA&nbsp;&nbsp;</option>
					<option value="ME" '.($prov_state == "ME" ? 'SELECTED' : '').' title="Maine">ME&nbsp;&nbsp;</option>
					<option value="MD" '.($prov_state == "MD" ? 'SELECTED' : '').' title="Maryland">MD&nbsp;&nbsp;</option>
					<option value="MA" '.($prov_state == "MA" ? 'SELECTED' : '').' title="Massachusetts">MA&nbsp;&nbsp;</option>
					<option value="MI" '.($prov_state == "MI" ? 'SELECTED' : '').' title="Michigan">MI&nbsp;&nbsp;</option>
					<option value="MN" '.($prov_state == "MN" ? 'SELECTED' : '').' title="Minnesota">MN&nbsp;&nbsp;</option>
					<option value="MS" '.($prov_state == "MS" ? 'SELECTED' : '').' title="Mississippi">MS&nbsp;&nbsp;</option>
					<option value="MO" '.($prov_state == "MO" ? 'SELECTED' : '').' title="Missouri">MO&nbsp;&nbsp;</option>
					<option value="MT" '.($prov_state == "MT" ? 'SELECTED' : '').' title="Montana">MT&nbsp;&nbsp;</option>
					<option value="NE" '.($prov_state == "NE" ? 'SELECTED' : '').' title="Nebraska">NE&nbsp;&nbsp;</option>
					<option value="NV" '.($prov_state == "NV" ? 'SELECTED' : '').' title="Nevada">NV&nbsp;&nbsp;</option>
					<option value="NH" '.($prov_state == "NH" ? 'SELECTED' : '').' title="New Hampshire">NH&nbsp;&nbsp;</option>
					<option value="NJ" '.($prov_state == "NJ" ? 'SELECTED' : '').' title="New Jersey">NJ&nbsp;&nbsp;</option>
					<option value="NM" '.($prov_state == "NM" ? 'SELECTED' : '').' title="New Mexico">NM&nbsp;&nbsp;</option>
					<option value="NY" '.($prov_state == "NY" ? 'SELECTED' : '').' title="New York">NY&nbsp;&nbsp;</option>
					<option value="NC" '.($prov_state == "NC" ? 'SELECTED' : '').' title="North Carolina">NC&nbsp;&nbsp;</option>
					<option value="ND" '.($prov_state == "ND" ? 'SELECTED' : '').' title="North Dakota">ND&nbsp;&nbsp;</option>
					<option value="OH" '.($prov_state == "OH" ? 'SELECTED' : '').' title="Ohio">OH&nbsp;&nbsp;</option>
					<option value="OK" '.($prov_state == "OK" ? 'SELECTED' : '').' title="Oklahoma">OK&nbsp;&nbsp;</option>
					<option value="OR" '.($prov_state == "OR" ? 'SELECTED' : '').' title="Oregon">OR&nbsp;&nbsp;</option>
					<option value="PA" '.($prov_state == "PA" ? 'SELECTED' : '').' title="Pennsylvania">PA&nbsp;&nbsp;</option>
					<option value="RI" '.($prov_state == "RI" ? 'SELECTED' : '').' title="Rhode Island">RI&nbsp;&nbsp;</option>
					<option value="SC" '.($prov_state == "SC" ? 'SELECTED' : '').' title="South Carolina">SC&nbsp;&nbsp;</option>
					<option value="SD" '.($prov_state == "SD" ? 'SELECTED' : '').' title="South Dakota">SD&nbsp;&nbsp;</option>
					<option value="TN" '.($prov_state == "TN" ? 'SELECTED' : '').' title="Tennessee">TN&nbsp;&nbsp;</option>
					<option value="TX" '.($prov_state == "TX" ? 'SELECTED' : '').' title="Texas">TX&nbsp;&nbsp;</option>
					<option value="UT" '.($prov_state == "UT" ? 'SELECTED' : '').' title="Utah">UT&nbsp;&nbsp;</option>
					<option value="VT" '.($prov_state == "VT" ? 'SELECTED' : '').' title="Vermont">VT&nbsp;&nbsp;</option>
					<option value="VA" '.($prov_state == "VA" ? 'SELECTED' : '').' title="Virginia">VA&nbsp;&nbsp;</option>
					<option value="WA" '.($prov_state == "WA" ? 'SELECTED' : '').' title="Washington">WA&nbsp;&nbsp;</option>
					<option value="WV" '.($prov_state == "WV" ? 'SELECTED' : '').' title="West Virginia">WV&nbsp;&nbsp;</option>
					<option value="WI" '.($prov_state == "WI" ? 'SELECTED' : '').' title="Wisconsin">WI&nbsp;&nbsp;</option>
					<option value="WY" '.($prov_state == "WY" ? 'SELECTED' : '').' title="Wyoming">WY&nbsp;&nbsp;</option></select>
		&nbsp;<span class="Label">Postal Code:</span> <input type="text" name="PCZip" maxlength="7" style="width:20%;" value="'.$pcZip.'" tabindex="31" /></td>
	</tr>');
//	</tr></table>');
//echo ("\n\t".'<table align="center" width="100%" cellpadding="0" cellspacing="2" style="border:2px solid red;border-radius:5px;">');
//echo ("\n\t".'<table align="center" width="100%" cellpadding="0" cellspacing="2" style="border:2px solid red;border-radius:5px;">');
//echo ('	<tr>
//		<td style="width:30%;" class="Label">Address (Alt):</td>
//		<td style="width:70%;"><textarea name="SecAddress" rows="3" cols="26" wrap="virtual" tabindex="32" oninput="enable_submit_personal_button()">'.$sec_address.'</textarea></td>
//	</tr>');
//echo ('	<tr>
//		<td style="width:30%;" class="Label">City:</td>
//		<td style="width:70%;"><input type="text" name="SecondaryCity" maxlength="32" size="16" value="'.$sec_city.'" tabindex="33" oninput="enable_submit_personal_button()" /></td>
//	</tr>');
//echo ('	<tr>
//		<td colspan="2"><span class="Label">Prov/State:</span> <select name="ProvState" tabindex="34" style="cursor:pointer" oninput="enable_submit_personal_button()">
//					<option value="">&nbsp;</option>
//</select>
//			&nbsp;<span class="Label">PC/ZIP:</span> <input type="text" name="PCZip" maxlength="16" size="2" value="'.$postal_Zip.'" tabindex="35" oninput="enable_submit_personal_button()" /></td>
//	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Country:</td>
		<td style="width:70%;"><input type="text" name="Country" maxlength="32" size="16" value="'.$country.'" tabindex="36" oninput="enable_submit_personal_button()" /></td>
	</tr></table>');
echo ("\n\t".'<table align="center" width="100%" cellpadding="0" cellspacing="2" style="border:2px solid red;border-radius:5px;">');
echo ("\n\t".'<tr>
		<td style="width:30%;" class="Label">Medical Details:</td>
		<td style="width:70%;"><textarea name="Medical" rows="4" cols="29" wrap="virtual" tabindex="28" oninput="enable_submit_personal_button()">'.$medical.'</textarea></td>
	</tr>');
echo ('</table>');
echo ("\n\t".'<table border="0" align="center" style="width:100%;" cellpadding="0" cellspacing="2">');
echo ('	<tr>
		<td style="width:30%;" class="Label">Interests:</td>
		<td style="width:70%;"><input type="text" name="Interests"  maxlength="12864" style="width:80%;" value="'.$interests.'" tabindex="15" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ("\n\t".'<tr>
		<td style="width:30%;" class="Label">Transportation Mode:</td>
		<td style="width:70%;"><select name="TransportationMode" onclick="enable_submit_personal_button()">'."\n");
		if ($state == "Update")
			{
			for ($i=0;$i<$num_array_transport;$i++) 
				{
				echo ('		<option ' . ($transport_mode == $transport_ID[$i] ? 'SELECTED' : '') . ' value="' .$transport_ID[$i] . '">' . $transport_desc[$i] .'</option>'."\n");
				}
			}
		elseif ($state == "Create")
			{
			for ($i=0;$i<=$num_array_transport;$i++) 
				{
				echo ('		<option value="' .$transport_ID[$i] . '">' . $transport_desc[$i] .'</option>'."\n");
				}
			}
echo ('		</select></td></tr>');
echo ("\n\t".'<tr>
		<td style="width:30%;" class="Label">First Aid Training:</td>
		<td style="width:70%;"><input type="checkbox" name="FirstAidTraining_Check" value="1" '. ($first_aid_training_check == 1 ? 'CHECKED' : '') .'  style="vertical-align:middle" oninput="enable_submit_personal_button()" />&nbsp;<span  class="Label">Previous Martial Arts Training:</span><input type="checkbox" name="PreviousMartial_Check" value="1" '. ($previous_martial_check == 1 ? 'CHECKED' : '') .'  style="vertical-align:middle" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ("\n\t".'<tr>
		<td style="width:30%;" class="Label">Admin Notes:</td>
		<td style="width:70%;"><textarea name="AdminNotes" rows="3" cols="29" wrap="virtual" tabindex="28" oninput="enable_submit_personal_button()">'.$admin_notes.'</textarea></td>
	</tr>');
echo ('</table>');
echo ("\n".'</div><!-- end middle record column "pers_profile_col2" -->');
	// right record column div
echo ("\n".'<div class="pers_profile_col3"><!-- begin right record column -->');
echo ("\n\t".'<table border="0" align="center" width="100%" cellpadding="0" cellspacing="2">');
// display the member's portrait on file
echo ('	<tr><td colspan="2">&nbsp;</td></tr><tr>
		<td colspan="2" align="center">');
		// display the default no-database image on the form for when state is create
		if ($state == "Create")
			{ echo ('<img src="../'.$portrait_url.'/'.$portrait_file.'" alt="" width="40%" class="box" />'); }
		else
			{ echo ('<img src="../'.$portrait_url.'/'.$portrait_file.'" alt="" width="40%" class="box" />'); }
echo ('	<br />&nbsp;</td>');
echo ('	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label"><img src="images/icons/note.gif" style="vertical-align:middle;width:20px;margin-left:3px;cursor:help;" alt="" title="The portrait to be integrated into this record must first be uploaded to the portraits directory residing under the web site images directory located under \'database/images/portaits/*\'." />&nbsp;Portrait File:</td>
		<td style="width:70%;"><input type="text" name="Portrait_File" maxlength="128" style="width:80%;" alt="" tabindex="37" ');
		// display the default URL for the no-datbasebase image on the form for when state is create
		if ($state == "Create")
			{ echo (' value="recruit_male.jpg" />'); }
		else
			{ echo (' value="'.$portrait_file.'" oninput="enable_submit_personal_button()" /></td></tr>'); }
echo ('	<tr>
		<td style="width:30%;" class="Label"><img src="images/icons/note.gif" style="vertical-align:middle;width:20px;margin-left:3px;cursor:help;" alt="" title="The default portrait directory is located under \'members_only/images/portaits/*\'." />&nbsp;Portrait URL:</td>
		<td style="width:70%;"><input type="text" name="Portrait_URL" maxlength="128" style="width:80%;" alt="" tabindex="38" ');
		// display the default URL for the no-datbasebase image on the form for when state is create
		if ($state == "Create")
			{ echo ('value="'.$portrait_url.'" />'); }
		else
			{ echo ('value="'.$portrait_url.'" oninput="enable_submit_personal_button()" /></td></tr>'); }
echo ('	<tr>
		<td style="width:30%;" class="Label">Comments:</td>
		<td style="width:70%;"><textarea name="Comments" rows="6" cols="28" wrap="virtual" tabindex="39" oninput="enable_submit_personal_button()">'.$comments.'</textarea></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Acad. Degree:</td>
		<td style="width:70%;"><input type="text" name="AcadDegree" maxlength="256" style="width:50%;" value="'.$acad_degree.'" tabindex="40" oninput="enable_submit_personal_button()" /></td>
	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Acad. Institution:</td>
		<td style="width:70%;"><input type="text" name="AcadInstitute" maxlength="256" style="width:80%;" value="'.$acad_institution.'" tabindex="41" oninput="enable_submit_personal_button()" /></td>
	</tr>');
//echo ('	<tr>
//		<td style="width:30%;" class="Label">Skills:</td>
//		<td style="width:70%;"><textarea name="Skills" rows="1" cols="28" wrap="virtual" tabindex="42" oninput="enable_submit_personal_button()">'.$skills.'</textarea></td>
//	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Biography:</td>
		<td style="width:70%;"><textarea name="Biography" rows="5" cols="28" wrap="virtual" tabindex="43" oninput="enable_submit_personal_button()">'.$biography.'</textarea></td>
	</tr>');
echo ('</table>');
echo ("\n".'</div><!-- end right record column "pers_profile_col3" -->');
echo ("\n".'<table width="100%" style="background-color:orange;">'."\n");
if ($state == "Update")
	{
?>
	<tr>
		<td align="center"><input type="submit" class="button" value="Enter to save personal profile update(s)" name="submit_personal_button" id="submit_personal_button" disabled="true" /> <input type="reset" class="button"  value="Clear Recent Updates from Form" /></td>
	</tr>
<?php
	}
elseif ($state == "Create")
	{
?>
	<tr>
		<td align="center"><input type="submit" class="button" value="Enter to save new personal profile record" name="submit_personal_button" id="submit_personal_button" disabled="true" /> <input type="reset" class="button"  value="Clear Recent Entries from Form" /> <input type="submit" class="button" value="Cancel New Record Entry" name="submit_cancel_personal_button" id="submit_cancel_personal_button" disabled="true" /></td>
	</tr>
<?php
	}
echo ('	</table></form><!-- end Personal_Profile_Form -->'."\n");
echo ("\n".'</div><!-- end personal_profile_main box -->'."\n");
// end main div object for presenting entire membership record	</section>
?>
ersonal_button()" /></td>
	</tr>');
//echo ('	<tr>
//		<td style="width:30%;" class="Label">Skills:</td>
//		<td style="width:70%;"><textarea name="Skills" rows="1" cols="28" wrap="virtual" tabindex="42" oninput="enable_submit_personal_button()">'.$skills.'</textarea></td>
//	</tr>');
echo ('	<tr>
		<td style="width:30%;" class="Label">Biography:</td>
		<td style="width:70%;"><textarea name="Biography" rows="4" cols="30" wrap="virtual" tabindex="43" oninput="enable_submit_personal_button()">'.$biography.'</textarea></td>
	</tr>');
echo ('</table>');
echo ("\n".'</div><!-- end right record column "pers_profile_col3" -->');
echo ("\n".'<table width="100%" style="background-color:orange;">'."\n");
if ($state == "Update")
	{
?>
	<tr>
		<td align="center"><input type="submit" class="button" value="Enter to save personal profile update(s)" name="submit_personal_button" id="submit_personal_button" disabled="true" /> <input type="reset" class="button"  value="Clear Recent Updates from Form" /></td>
	</tr>
<?php
	}
elseif ($state == "Create")
	{
?>
	<tr>
		<td align="center"><input type="submit" class="button" value="Enter to save new personal profile record" name="submit_personal_button" id="submit_personal_button" disabled="true" /> <input type="reset" class="button"  value="Clear Recent Entries from Form" /> <input type="submit" class="button" value="Cancel New Record Entry" name="submit_cancel_personal_button" id="submit_cancel_personal_button" disabled="true" /></td>
	</tr>
<?php
	}
echo ('	</table></form><!-- end Personal_Profile_Form -->'."\n");
echo ("\n".'</div><!-- end personal_profile_main box -->'."\n");
// end main div object for presenting entire membership record	</section>
?>
