<?php
// Program: content_about_faqs_en.php
//	Description: source for the English textual content for FAQs (about_faqs.php)
//	2017 ------------------
//
// English content -------------------
$title[0] = "Frequently Asked Questions (FAQs)";
$faq_intro[0] = "As one can imagine, members of AEMMA experience frequently asked questions (FAQs) about our organization, our associations, our equipment, our training, and our mission. We have assembled the most frequently asked questions we are aware of so far and have made them available here as HTML. This FAQs is a work in progress and will change as our body of frequently asked questions grows.</p><p>We hope this helps to address the more common questions we regularly encounter. For your convenience, the current list of questions follows and are linked by clicking on the question of interest:";

$faq_q1[0] = "What is AEMMA?";
$faq_a1[0] = "<b>AEMMA</b> stands for the <b>A</b>cademy of <b>E</b>uropean <b>M</b>edieval <b>M</b>artial <b>A</b>rts. The AEMMA website is located at <a href=\"http://www.aemma.org\" target=\"_blank\"><b>www.aemma.org</b></a> for all the information about the Academy.  <b>AEMMA</b> is a non-profit corporation comprised of instructors and students who share a common interest in the preservation, promotion and furthering of historical European/Western martial arts.&nbsp; We seek to revive interest in the fighting arts practiced in Europe between the 12th and 15th centuries through the research, study and practice of the fighting arts, in particular, those described in detail in  <a href=\"../index2.php?pg=fl\" target=\"_blank\">Fiore dei Liberi's</a> treatises entitled <i>Flos Duellatorum</i>, <i>Fior di Battaglia</i> and <i>Florius de arte luctandi</i>.";

$faq_q2[0] = "Why would I join AEMMA?";
$faq_a2[0] = "Joining AEMMA provides you with numerous opportunities learn more about the fighting art prevalent during that period, to learn more about medieval history and to exchange ideas, discussions and questions with individuals at AEMMA who possess a great deal of experiernce and knowledge in the art and medieval history, and all the while, learning self-defence and offensive techniques as well as enhancing your physical conditioning and well being. Of course, you get to play with really cool toys such as swords, spears, daggers and so forth!";

$faq_q3[0] = "What would I get out of AEMMA as a member?";
$faq_a3[0] = "There are at least six benefits that one can derive from being a member of AEMMA: <ol><li>Firstly, to enhance your personal growth and development through training and learning the art manifesting itself into self-defence and offensive techniques applicable to most physical confrontations one might face today.</li><li>Secondly, to enhance your own knowledge and appreciation of the medieval period, through discussions and social intercourse with members, some of whom are studying the medieval period at a university level, while others have garnished over many years, much knowledge and expertise in the subject matter.</li><li>Thirdly, the satisfaction derived from participating and engaging in an activity which preserves, promotes and furthers an ancient fighting art, one which is an important attribute of Western culture.</li><li>Fourthly, you would get numerous opportunities to network and/or make friends with outstanding individuals that you would otherwise never have a chance to meet.</li><li>Fifthly, if one is trying to build an acting resume (CV), this form of martial arts training and skills development could be an additional skill highlighted in your acting resume.  We, at AEMMA, would even be honoured to be one of your references if that'll help.</li><li>And lastly, it's a fabulous and fun way to spend one's time and improve one's fitness and skills to boot!</li></ul>";

$faq_q4[0] = "Are there any women training at AEMMA?";
$faq_a4[0] = "Yes. We encourage both male or female, who wish to learn and train in these arts and to expand their knowledge and appreciation of the medieval period, to join us.";

$faq_q5[0] = "Where and when are AEMMA's classes held?";
$faq_a5[0] = "The training facility in Toronto is located at <a href=\"../index2.php?pg=a6\" target=\"_blank\">927 Dupont Street, 2nd floor</a> (above the Master Mechanic) near the intersection of Ossington and Dupont, on the south-east corner of Dupont and Concord, downtown Toronto, Ontario, Canada. Classes are <a href=\"../index2.php?pg=a4\" target=\"_blank\">scheduled</a> for Sunday mornings through to Sunday afternoon till 3pm, Monday and Wednesday evenings between 7:00 and 10:30pm, archery training sessions (medieval longbow) on every Saturday.</p><p>For training schedules and locations at any one of our other chapters, please visit their portal for further information on this website.";

$faq_q6[0] = "Does AEMMA just do sword training, or are other styles researched and practised as well?";
$faq_a6[0] = "AEMMA incorporates not only <a href=\"../index2.php?pg=h3\" target=\"_blank\">longsword</a> training, but <a href=\"../index2.php?pg=h3\" target=\"_blank\">arming sword</a>, <a href=\"../index2.php?pg=h3\" target=\"_blank\">sword & buckler</a>, <a href=\"../index2.php?pg=h4\" target=\"_blank\">armour</a>, <a href=\"../index2.php?pg=h1\" target=\"_blank\">grappling</a> and <a href=\"../index2.php?pg=h2\" target=\"_blank\">dagger</a> techniques as described in the 14th and 15th century manuscripts, in other words, a complete fighting system.  Training in grappling and dagger are considered foundational for study and practice historical European martial arts, and which will develop the student's sensitivity, timing, judgment, distance and targeting.  These are critical attributes important for every martial artist regardless of whether one is training in historical European martial arts or Eastern martial arts systems. AEMMA also investigates and practise with <a href=\"../index2.php?pg=h5\" target=\"_blank\">quarter staff, spear, poleaxe</a> and <a href=\"../index2.php?pg=h6\" target=\"_blank\">traditional archery</a> (longbow, recurve) techniques.";

$faq_q7[0] = "Does AEMMA make use of padded weapons in its training programs?";
$faq_a7[0] = "No. We feel that padding a weapon radically alters its movement and performance characteristics rendering the use of such altered weapons useless to anyone wishing to study historically accurate weapons arts. We use aluminum practise swords for unarmoured and lightly armoured training and move the student to steel blunted weapons if/when (s)he acquires the proper armour required for steel weapons training. Although, just for fun, we have been known to play with light sabres every once in a while!";

$faq_q8[0] = "Isn't all that equipment expensive?";
$faq_a8[0] = "To a degree, yes. If you're going to go all the way to fully armoured combat, then yes, there is a certain level of expense to be expected. However, any sport requiring more than a ball and/or stick will be expensive to some degree. We find the expense level required by our \"full steel\" program to be somewhat less expensive than sports such as SCUBA diving and hang gliding, and in line with mountain climbing and skiing. Armoured steel fighting is far more expensive than soccer or basketball and slightly more expensive than ice hockey. However, it is considerably less expensive than sports like motocross or rally racing. Recruits however, have to incur very little up-front expenses for their <a href=\"../index2.php?pg=t10\" target=\"_blank\">recruit level of equipment</a>, encompassing only an AEMMA t-shirt, training leggings, flat-soled training shoes and leather garden-variety gloves all for about $100 in order to get started with training at AEMMA.</p><p>Most \"extreme\" sports aren't inexpensive. It's just a fact of life.";

$faq_q9[0] = "Has anyone been hurt in AEMMA?";
$faq_a9[0] = "Minor injuries like scrapes, sprains and bruises have occured, which is the norm in most physically-oriented sport or martial arts training. The most serious injuries which have occurred during training over the last five year period has been a broken thumb during unarmoured fencing with longswords and a stab to the hand (fleshy part of the thumb) by a blunted steel longsword during armoured practice.</p><p>AEMMA (FACT) also have on-site, an automated electronic defibrillator or <b>AED</b>. An <b>AED</b> is a portable device that checks the heart rhythm and can send an electric shock to the heart to try to restore a normal rhythm. AEDs are used to treat sudden cardiac arrest (SCA). SCA is a condition in which the heart suddenly and unexpectedly stops beating.";

$faq_q10[0] = "Are there tournaments, and if so, how frequent are they and where are they held?";
$faq_a10[0] = "Armoured Tournaments, or more accurately, <a href=\"../index2.php?pg=t4\" target=\"_blank\"><i>pas d'armes</i></a> are scheduled more or less annually and are hosted either at the <a href=\"http://www.rom.on.ca\" target=\"_blank\">Royal Ontario Museum</a> (ROM) or at AEMMA's <a href=\"../index2.php?pg=a6\" target=\"_blank\">salle d'armes</a>.  Other armoured tournaments (<i>pas d'armes</i>) are organized and hosted by the <a href=\"http://www.ottawasword.com\" target=\"_blank\">Ottawa Medieval Sword Guild</a> (OMSG) during their annual OMSG Camping Weekend. AEMMA also hosts an <a href=\"../index2.php?pg=t8\" target=\"_blank\">annual unarmoured tournaments</a> in Toronto opened to all practioners of historical European martial arts for individuals who have achieved the rank of <a href=\"../index2.php?pg=t01\" target=\"_blank\">schollers</a> or above.";

$faq_q11[0] = "Is AEMMA associated with or related to the Society for Creative Anachronism (SCA)?";
$faq_a11[0] = "No. Nor are we associated nor affiliated with any other recreationist, re-enactment, role playing or fantasy group. We are a martial arts academy which has similar training objectives as any Eastern martial arts academy (e.g. Karate, Kung Fu, Wing Chun, Judo, etc.).  AEMMA members over time have had former members of the <a href=\"http://www.sca.org\" target=\"_blank\">SCA</a>.  We encourage anyone who does have an interest in medieval culture, politics, arts and crafts to explore those interests and therefore, we recognise that the <a href=\"http://www.sca.org\" target=\"_blank\">SCA</a> and its affiliates may offer opportunities to further explore those interests. </p><p>We hope that in the future, Western Martial Arts academies such as AEMMA will be more numerous and offer those who wish to explore accurately restored medieval fighting arts an avenue to further those interests.";

$faq_q12[0] = "Is AEMMA a reenactment or theatrical group?";
$faq_a12[0] = "No. Our purpose is not to perform medieval re-enactments or deliver plays in medieval theatre. However, we are more than willing to train interested individuals engaging in theatrical and/or re-enactment combat in the art of medieval combat as taught by the medieval masters.</p><p>That said, AEMMA has been involved in a number of films, in particular, documentaries in which anywhere from one to a dozen AEMMA students are actively involved in the film. The following is a partial list of films/documentaries:<ul><li>Battle of Kings - Bannockburn 1314 - a docu-drama that examines and highlights Robert the Bruce, and the battle of Bannockburn, the first major victory by the Scotts over the English. The project involved 12 AEMMA individuals, included mounted combat, partially filmed in Scotland, and partially filmed in Halifax. 2013;</li><li>Documentary, TV series: M5 Weapons of War – The Damascus Sword, 2010 – domain expert (swords and sword fighting);</li><li>Discovery Channel, Daily Planet: Natasha Stillwell takes a behind the scenes look at “armizare” - 2006;</li><li>Timeline: a science fiction adventure film, whereby a professor stumbles into a wormhole and plunges back in time to 14th century France. Filmed in Quebec, involved one individual from the Ottawa group. 2003</li><li>Discovery Channel: Examining the resurrection of European medieval martial arts in Canada, co-hosted by the Royal Ontario Museum, 2001</li></ul>";

$faq_q13[0] = "What is the difference between AEMMA and a re-enactment group?";
$faq_a13[0] = "In general, a re-enactment group will act out some previous historical event and therefore, would script or structure the engagements for the purpose of entertainment.  Although they may occassionally employ historical techniques in their \"fighting\", the outcome of every bout is planned accordingly.  Whereas, at AEMMA, the training orientation is martial arts, or in other words, the \"arts of war\".  Therefore, the intent of the bouts is martial, which is exactly similar as bouts in boxing, judo, karate, or any other fighting arts and to add, the outcome of the bouts are never known, given that both combatants fully expect to be victorious.";

$faq_q14[0] = "Aren't those swords really heavy?";
$faq_a14[0] = "Not really. An 11th-12th century sword, similar to those used by Saxons, Vikings and Normans, would weigh about 2 1/2 - 3 pounds (1.1 - 1.35 kilograms).&nbsp; A 13th-14th century hand-and-a-half sword would weigh 3 to 3 1/2 pounds (1.35 - 1.6 kilograms). 14th - 15th century longswords would weigh 3 1/2 - 4 1/2 pounds (1.6 - 2 kilograms) whereas, arming swords would weigh in between 2 1/2 to 3 1/2 lbs (1.1 - 1.6 kg).</p><p>AEMMA's steel weapons are about 3/4 pound (350 grams) heavier on average than their medieval counterparts due to the fact that our weapons are not sharp. Sharpening removes material, and thus weight, from a blade.</p><p>One should be aware that slashing and thrusting an overly heavy sword would tire a fighter out far too quickly, making him vulnerable. Medieval swordsmiths were indeed aware of this fact and strived to make their weapons as light as possible without sacrificing the blade's strength.";

$faq_q15[0] = "Weren't European medieval knights just a bunch of barbarian thugs with no fighting finesse?";
$faq_a15[0] = "Hardly. Please be aware that medieval knights began their training at a very young age, typically 7-8 years old, and did not become knights until the age of 21. A knight's training lasted all his life and when not on active campaign, knights engaged in regular tournaments to maintain and display their skills.</p><p>Knights, being fighting noblemen, were essentially a professional fighting class within the noble classes and were rightly feared by non-professionals on the battlefield. It was normal for noble youngsters to be sent out to be fostered by other noble families to receive their knightly training and their fathers were keen to seek out fellow nobles with a reputation for providing the best training and education for the fosterlings in their care.  As such, knights tended to be literate, schooled in theology, rhetoric, poetry and Latin, and were highly trained skilled warriors.</p><p>If you're looking for barbarian thugs, look back to the Dark Ages (AD 300-900) and we're not sure that they fought like barbarian thugs!";

$faq_q16[0] = "Isn't all that armour heavy and difficult to fight in?";
$faq_a16[0] = "Depends on your definition of difficult. Medieval armourers went to great lengths to construct armour that would be as light as possible and as unrestricting to movement as possible. The image of knights clad in 300 pounds (135 Kilos) of armour being hoisted in to the saddle by cranes was a misconception started in the Victorian era. Since the actual histories frequently tell of knights who were unhorsed and then managed to fight their way to another mount it seems plain to us that these acts could not have happened if the knight was encumbered by too much weight and restricted freedom of movement. In fact a late 14th - early 15th century full harness for a normal sized knight would weigh at most 65 pounds (30 Kilos) and if properly made and tailored, would hinder the knight as little as possible.</p><p>What did affect knights in armour was heat. Fighting in armour on a hot day brings more discomfort from heat than from weight. Even on a not-so-hot day a knight fighting in full armour would heat up rather quickly.";

$faq_q17[0] = "Are your swords sharp?";
$faq_a17[0] = "No. That would be far too dangerous! Our swords are blunt. They are known as \"<a href=\"glossary.html#rebated\">rebated</a>\" weapons which were typically used during medieval tournaments.  We do possess and use of sharpened steel swords for \"<a href=\"../onlineResources/sharpTest.htm\">cutting practise</a>\" using a moistened tatami mat on a spike as a target. We will never use sharpened swords for combat against our fellow fighters.";

$faq_q18[0] = "Don't I have to be some sort of muscle bound Conan-style barbarian to engage in this form of fighting art?";
$faq_a18[0] = "No. Actually being over muscled would be more of a hindrance than a help. Good physical conditioning which enhances one's speed, and flexibility are much more useful than bulky muscles that get in the way of eloquently swinging a sword. A good level of muscle tone is important, and can be achieved without becoming muscle-bound. Our training seeks to enhance these attributes and include conditioning exercises at the beginning of each class.";

$faq_q19[0] = "Aren't you kinda old to be doing this?";
$faq_a19[0] = "Who says we're old? AEMMA members' ages range from their 20's to their 50's, which in a medieval context is admittedly a little late to start training. Knights did, as mentioned above, start training as young as 7 years old. Unfortunately, starting weapons training for 7 year olds is difficult in these litigious times unless one can afford the best lawyers. Besides, when we were 7 nobody was doing this.</p><p>Medieval knights tended to keep at their trade until they were either killed in action or just became too old to do it anymore. Since we are all in fine trim and full of youthful energy, regardless of any encroaching grey hair, we all feel young enough to practise this art. We only regret not having the opportunity of exploring western martial arts in childhood. </p><p>There are accounts of knights who demonstrated great prowess in tournaments and battle, a brief list of notables follow: <ul><li>Around 1190 Prior Philip of St Frideswide in Oxford talked of a knight, Hamo de St-Ciry, taking to the road in pilgrimage to the tomb of Becket, falling ill there for a fortnight, and travelling on from Canterbury to visit some cousins in Berkshire on a social call. Hamo was at the time over ninety (90) years of age, and had been blind and deaf for three and a half years.</li><li>Roger de Mowbray (Lord of Montbray) died at the age of 68 (b:c1120 d:1188) a warrior, crusader and generous with a donation of two carucates of land (c.240 acres), a house and two mills to the Order of St. Lazarus.</li><li>Hugues de Payens (b:1070 d:1136) was the co-founder and first Grand Master of the Knights Templar. He also authored the <i>Latin Rule</i> which is the code of behaviour followed by the Order. He died at the age of 66.</li><li>Ulrich von Liechtenstein (b: 1200 d: 1275) was a German minnesinger and poet of the Middle Ages. He was also an exceptional jouster, often wearing female attire while jousting. He died at the age of 75.</li><li>William Marshall, 1st Earl of Pembroke, born c.1146, d. 1219.  According to some accounts, William Marshal still engaged in armoured tournaments well into his 60's. Marshall died at the age of 73.</li><li>Sir John Hawkwood (b: 1320 d: 1394) was an English mercenary or condottiere who died at the age of 74. The French chronicler jean Froissart knew him as Jean Haccoude and also Giovanni Acuto.</li><li>G&ouml;tz von Berlichingen (b:1480 d:1562) was also known as G&ouml;tz of the Iron Hand, was an outstanding warrior, and fought in 15 feuds. In one battle during the siege of the city of Landshut, he lost his right arm when an enemy cannon fire forced his sword against him and severed his arm off. He had two mechanical prosthetic arms made which allowed him to continue fighting.  He is also famous for the vulger expression \"he can lick my arse\". He died at the ripe old age of 82.</li></ul></p><p>Better late than never.";

$faq_q20[0] = "Aren't you too tall to be a knight?&nbsp; After all, the armour you see in the museums seem to indicate a short man, and the doorways in the castles are certainly very low?";
$faq_a20[0] = "While it is true that the average European was shorter in Medieval times than today, the difference is not that much. At most we are 3 inches (7.5 cm) taller today, on average, than our forebears were. For those of us with Nordic heritage, the difference is even smaller. Even in the Middle Ages, very tall individuals were known to exist. The Frankish emperor Charlemagne (8th - 9th century) was 6 feet 4 inches (193 cm) tall. King Harald Sigurdsson Hardraada of Norway (11th century) was nearly 7 feet (well over two metres) tall. There is also a suit of armour from c. 1500 on display in Edinburgh, Scotland which was built for a 7 foot (213 cm) tall man.</p><p>Knights and other nobles tended to be better fed than your average serf. This being so, they were on average somewhat larger than the European average.</p><p>To complicate matters, suits of armour on display tend to compact to a smaller size than their wearers unless they are mounted on mannequins of a size identical to their wearers. This is why armour on dislplay tends to be noticeably smaller than the average person.</p><p>Castles had small doorways for defense reasons. If invaders had to crouch to get through a doorway, it made them vulnerable to attack from upright standing defenders on the other side of the door.</p><p>With one notable exception, the male members of AEMMA all seem to be hovering around the six foot (183 cm) mark, some may be taller, some may be shorter. We feel there is nothing wrong with this.";

$faq_q21[0] = "Do you incorporate chivalry in your organization or training system?";
$faq_a21[0] = "No. We cannot ignore the fact that chivalry did play a role in the historical martial arts and feel an understanding of this historic role is highly conducive to understanding the history of western fighting arts and its practitioners. That said, no specific religion based code of ethics is endorsed by AEMMA nor is it on our curriculum.   We do, however, through example foster desireable \"warrior\" attributes such as, we treat each other with respect, and exhibit other attributes such as discipline, honour, courtesy, humility, loyalty and dignity to name a few. These attributes may in some ways be similar to some of the chivalric ideals, however, that would be the only similarity.";

$faq_q22[0] = "Where do you get your armour and equipment from?";
$faq_a22[0] = "We source our equipment from individuals who have made armour as a hobby, or have made armour for other re-enactment groups and also others who've made armour for the entertainment/film industry. We work closely with a number of armourers in order to have armour constructed that is as historically accurate as possible.  We do our best to promote new \"talent\" in this area.  Some of our sources include locations such as Halifax, Montreal and Calgary.  Links to these and other <a href=\"../index2.php?pg=v0\" target=\"_blank\">sources are available on the website</a>.";

$faq_q23[0] = "How much did the armour cost in today's dollars?";
$faq_a23[0] = "The cost of armour in today's dollar is somewhat subjective. Based on information found in references located in the link <a href=\"medievalprices.php\">Medieval Price List</a>, if one uses the cost of chickens as a basis (a chicken would've cost 8 pence in the 14th century), a full harness (armour) owned by a knight would run approximately $5,300 US however, armour for the Prince of Wales (14th century) with \"gilt and graven\" would set you back approximately $108,800 US.  If one uses another basis, such as a cost of a house, for example a merchant's house ranged between $120,000 - $240,000 US (assuming a typical middle class dwelling), a complete armoured harness would range somewhere in the $60,000 US range.";

$faq_q24[0] = "How did the knight \"pee\" while wearing armour in battle?";
$faq_a24[0] = "While an individual is engaged in battle, the last thing on that person's mind is having to \"pee\". They were thinking about survival.  If, however, there was a \"break\" or pause in the battle and he/she must \"pee\", then they would simply \"pee\" in their armour.  This is no different than today's astronauts having to \"pee\" in their spacesuits.  At the conclusion of the battle, the knight's squires would have the responsibility of \"cleaning up the mess\".";
?>
