<?php
// Program: content_rnk_free_scholler_fr.php
//	Description: source for the textual content on the rank of free scholler page (rnk_free_scholler.php) (« »)
//	2017 ------------------
///
// French content -------------------
$title[1] 	= "Rank: Scholler";
$banner[1] 	= "<img src=\"../images/banner_scholler.jpg\" alt=\"\" width=\"100%\"/>";
$rnk_p11[1]	= "Le rang de <b>scholler</b> identifie un étudiant et praticien des arts martiaux européens historiques connus sous le nom de <i><b>l`arte dell`armizare</b></i> ou simplement comme <b><i>armizare</i></b> et est celui qui s'est engagé à apprendre et à s'entraîner dans l'art. Le <b>scholler</b> reconnaît que, pour devenir compétent dans cet art, comme pour tout autre système d'arts martiaux, c'est un choix de style de vie qui exige l'engagement et le dévouement nécessaires pour atteindre un niveau d'excellence qui enrichira La vie de l'étudiant à la fois intellectuellement et physiquement. Afin d'obtenir une compétence dans les niveaux les plus avancés, le chercheur doit s'efforcer de s'organiser pour permettre d'assister à des sessions de formation régulières. Le <b>scholler</b> doit se conformer aux règles et à la constitution de l'Académie et être prêt à obtenir l'armure et l'armure historiquement exactes pour les armes formées. <b>Scholler</b> formation est le plus long et le plus intense de tous les rangs.";
$rnk_p12[1]	= "C'est au cours de la formation <b>scholler</b> où l'élève apprend comment « lutter » devient un artiste martial qualifié, habile et compétent. Les principes fondamentaux appris et formés lors de la formation des recrues constituent la base sur laquelle les techniques avancées et les principes combatifs sont fondés. La structure de formation reflète le format de <a href=\"\" target=\"_top\"><i>Flos Duellatorum</i></a> de Fiore dei Liberi en termes de cartographie des segments de formation aux combats / armes Styles documentés dans le traité. Le scholler continuera à s'entraîner dans les composants de formation de base (<i>abrazare, daga, spada </i>) du programme de formation des recruteurs, mais approfondira ces segments de manière beaucoup plus profonde. Ces segments seront programmés tout au long de l'année, de sorte que, au fil du temps, un scholler aura l'opportunité de s'entraîner, de pratiquer et d'être testé dans chacun des segments.";
$rnk_p13[1]	= "Le programme de formation de Scholler englobera les styles suivants: <i>abrazare, daga, spada, spada e brocchiere, spada longa </i>, poleweapons: <i>azza e lanza</i> et <i>arme</i> pas nécessairement dans cet ordre. <b>À la fin du programme, le scholler est testé par les instructeurs.</b> Si le scholler passe le test <b>scholler</b>, il recevra un dague rondel représentant le prix avec succès terminé. Ce poignard rondel peut être porté par le scholler pendant la formation et les événements.";
$rnk_p14[1]	= "D'une perspective héraldique, <b>schollers</b> sont encouragés à devenir « <b>investis de blason</b> » afin que leurs armoiries puissent être suspendues sur le garde-meuble de la salle d Les armes auxquelles les badges schollar peuvent être attachés représentaient les segments terminés avec succès, et sous la forme de drapeaux ou de bannières lors de leur participation à des tournois ( blindés ou non ) ou d'autres événements, le cas échéant. Pour des exemples de bras actuellement possédés par schollers et plus haut, cliquez <a href=\"\"><b>ici</b></a>. Il existe un certain nombre de ressources pour aider à ce sujet, et il est impératif que les armes créées, supposées, matriculées, enregistrées, accordées soient héraldiques et, par conséquent, à cette fin, il existe un bon nombre de personnes dans AEMAM qui peuvent offrir Assistance et conseils. Vous trouverez plus d'informations au bas de cette section ( <b>scholler</b> ) en cliquant <a href=\"\"><b>ici</b></a>.";

$title_p2[1] 	= "Exigences de Scholler";
$rnk_l21[1]	= "a obtenu le rang de <b>scholler</b> en contestant avec succès et en complétant <font color=\"#461B7E\"><b>test scholler</b></font>,";
$rnk_l22[1]	= "<a href=\"\">frais de formation</a> sont payés régulièrement et il n'y a pas de frais exceptionnels,";
$rnk_l23[1]	= "possède le <a href=\"\">équipement minimum</a> comme requis pour le rang de <b>scholler</b>,";
$rnk_l24[1]	= "a pris l'initiative d'être « investi d'armes » qui a été approuvé par AEMAM ou <a href=\"http://www.gg.ca/heraldry\" target=\"_blank\">CHA</a>, cliquant <a href=\"#heraldry\"><img src=\"../images/coatofarms/tinyShield.gif\" valign=\"middle\" hspace=\"4\" border=\"0\" alt=\"\" class=\"fade\" title=\"Cliquez pour en savoir plus sur l'obtention d'un blason personnel\"></a> pour plus d'informations.";
?>
