<?php
// Program: content_rnk_intro_fr.php
//	Description: source for the textual content on the overview and introduction of the AEMMA ranking system page (rnk_intro.php) (« »)
//	2017 ------------------
///
// French content -------------------
$title[1] = "Introduction au système de classement de l'AEMAM";
$title_p1[1] = "Histoire";
$rnk_p11[1]	= "Le système de classement utilisé chez AEMMA repose sur les quatre notes définies dans le système des arts martiaux anglais au 16ème siècle, telles que définies dans la structure organisationnelle du « Quatre Anciens Maisters ». Dans l'ordre croissant, ils étaient: <b>scholler</b>, <b>scholler libre</b>, <b>provost</b> et <b> maister</b>. Le rang de « anciant maister » a été réservé comme titre de courtoisie pour avoir reconnu l'ancienneté au sein de l'organisation.";
$rnk_p12[1]	= "Les « Quatre Anciens Maisters » ou plus tard la <i>Société de Maisters</i> étaient une unité autoritaire et assez puissante dans l'Angleterre du XVIe siècle, spécifiquement à Londres. Il y a des éléments de leur pouvoir dans le « <i>Liber Albus</i> » contenant une législation qui s'appliquait à la Compagnie de Maisters leur accordait l'autorité totale d'emprisonner réellement des personnes qui étaient rebelles ou contraires aux Four Ancient Maisters. L'histoire des Four Ancient Maisters est compliquée avec Des preuves sommaires en nommant explicitement cette unité autoritaire. L'histoire pourrait être reliée à un mandat de 1540 dans lequel le roi Henri VIII a nommé le «Maîtres de la Science de la Défense» comme une commission, mais ne nomme pas l'organisation. Plus tard , Le roi James Ier, dans son mandat de 1605, a chargé les « Maîtres de la Noble Science de la Défense » avec les mêmes devoirs que ceux du mandat de 1540. Il a également omis de nommer explicitement l'organisation. Bien qu'il n'y ait pas de preuve concrète Ce qui prouve que les plusters étaient membres d'une société légalement constituée, les mandats mentionnés suggèrent fortement que tel était le cas. La société de Maisters avait à la fois des règles et de la constitution pour régir son mode de fonctionnement. Pour les références historiques, The Provosts Othe et The Maisters Othe peuvent être consultés en ligne.";

$title_p2[1] = "Aujourd'hui";
$rnk_p21[1]	= "Le système de classement décrit constitue la base des cinq (5) niveaux distincts employés aujourd'hui chez AEMMA: <b> recruteurs, scholler, scholler libre, provost</b> et <b>maestro</b>. Le mot <b>scholler</b> dérive d'un mot latin « <i>schola</i> » ou « école ». Par conséquent, étant donné qu'un étudiant ou un savant (ancien anglais) est quelqu'un qui étudie un sujet académique (en utilisant l'analogie « étudiant de fin de cycle »), cela a été jugé applicable au rang initial d'un étudiant d'arts martiaux de l'Ouest. Pour ce faire, un étudiant gratuit est celui qui subit une formation avancée, semblable à un étudiant diplômé dans une perspective académique. La composante académique ou de recherche de ce système de classement commence au début du classement « scholler » lors de la formation de l'élève avec sa participation à un projet de recherche existant ou en cours.";
$rnk_p22[1]	= "La désignation <b>provost</b> est accordée par l'organe directeur de l'école et est obtenue lorsque l'élève a la International Masters at Arms Federation a permis d'acquérir les compétences techniques les plus élevées d'une arme et qu'un projet de recherche est complété avec une soumission de document de recherche . A <b>provost</b>, par définition, est un individu qui est le chef ou le maître d'un collège ou d'un sujet particulier. L'utilisation de cette définition en ce qui concerne les arts martiaux comprendrait également les compétences en armes, les techniques pertinentes et leur histoire environnante. On peut utiliser l'analogie selon laquelle <b>provost</b> a obtenu un doctorat dans le type de cette arme particulière. A <b>maestro</b> est celui qui a reçu ce titre par un organe de direction externe ou un maestro existant.";
$rnk_p23[1]	= "L'une des étapes les plus importantes dans la progression du rang de <b>scholler</b> à <b>maestro</b> est la notion de « prix et défis ». La quête du prix de la promotion est une composante culturelle fondamentale de l'Académie, dans laquelle la plupart, sinon tous, souhaitent obtenir le prix grâce à un minimum de 3 défis contre les individus dans le rang suivant souhaité pour chaque arme en cours de formation. Le jeu pour le prix comprend deux étapes. La première étape se produit en tant qu'événement interne à l'Académie dans lequel les compétences de l'élève sont évaluées en privé par le corps de direction de l'AEMMA. La deuxième étape est que l'élève doit présenter un défi pour le prix de <b>scholler</b>, mais aucun étudiant n'est autorisé à présenter des problèmes jusqu'à ce que l'examen privé soit terminé et jugé réussi. Il n'y a pas de temps réel avant que l'élève ne puisse jouer pour le prix une fois que le défi a été soumis, mais il est généralement laissé à l'élève. Seul le <b>recruteur</b> et <b>scholler</b> possède cette option de prix dans la promotion pour <b>scholler</b> et <b>scholler libre</b> respectivement. Les rangs les plus élevés sont régis selon la structure du temps.";
$rnk_p24[1]	= "L'espoir de la formation est que l'élève, avec une pratique et un engagement réguliers, peut atteindre le niveau le plus élevé et le niveau de compétence, le maestro dans environ 5 à 10 ans. Cela a de grandes variations, en fonction de l'engagement de l'élève en matière de formation, de la fréquentation des cours, du développement de projets de recherche, de la disponibilité de l'élève à la formation, des capacités physiques, de l'endurance et de leurs compétences physiques naturelles de l'élève. La compétence et la sécurité sont primordiales dans le programme de formation.";

$rnk_l1[1]	= "<i>Liber Albus</i> (Livre blanc) contient les lois et coutumes de la ville de Londres, compilé en 1419, par John Carpenter, secrétaire de mairie.";
$rnk_l2[1]	= "Riley, H.T. (trans), 1861 <a href=\"https://archive.org/details/liberalbuswhiteb00carpuoft\" target=\"_blank\" title=\"Livre blanc\"><i>Liber Albus</i></a>";
$rnk_l3[1]	= "Brown, Terry. \"<a href=\"https://www.amazon.com/exec/obidos/ASIN/1898281181/academyofeuropea\" target=\"_blank\"><i>English Martial Arts</i></a>\". 1997";
?>
