<?php
// Program: content_rnk_intro_en.php
//	Description: source for the English textual content on the introduction to ranks page (rnk_intro.php)
//	2017 ------------------
//
// English content -------------------
$title[0] = "Introduction to AEMMA's Ranking System";
$title_p1[0] = "History";
$rnk_p11[0]	= "The ranking system employed at AEMMA is based on the four grades defined in the English martial arts system in the 16th century as defined in the organizational structure of the \"Four Ancient Maisters\". In ascending order, they were: <b>scholler</b>, <b>free scholler</b>, <b>provost</b> and <b>maister</b>. The rank of \"anciant maister\" was reserved as a title of courtesy for acknowledging seniority within the organization.";
$rnk_p12[0]	= "The \"Four Ancient Maisters\" or later the Company of Maisters were an authoritive unit and quite powerful in the sixteenth century England, specifically in London. There is evidence of some elements of their power in the \"<i>Liber Albus</i>\" containing legislation that which applied to the Company of Maisters grants them total authority to actually imprison individuals who were rebellious or contrary to the Four Ancient Maisters. The history of the Four Ancient Maisters is convoluted with scanty evidence naming this authoritive unit explicitly. The history could be linked back to a warrant of 1540 in which King Henry VIII appointed the \"Masters of the Science of Defence\" as a commission, however, does not actually name the organization. Later, King James I, in his warrant of 1605 charged the \"Masters of ye Noble Science of Defence\" with the same duties as those of the Warrant of 1540. He too failed to name the organization explicitly. Although there is no concrete evidence proving that the maisters were members of a legally constituted company, the warrants mentioned strongly suggest that such was indeed the case. The Company of Maisters had both rules and constitution to govern its mode of operation. For historical references, The Provosts Othe and The Maisters Othe can be viewed online.";

$title_p2[0] = "Today";
$rnk_p21[0]	= "The ranking system described forms the basis of the five (5) distinct levels employed today at AEMMA: <b>recruit, scholler, free scholler, provost</b> and <b>maestro</b>. The word <b>scholler</b> is derived from a Latin word \"<i>schola</i>\" or \"school\". Therefore, given that a scholar or scholler (old English) is someone who studies an academic subject (using the \"under-graduate student\" analogy), this was found to be applicable to the initial rank of a western martial arts student. Taking this further, a free scholler is one who is undergoing advanced training, similar to a graduate student from an academic perspective. The academic or research component of this ranking system begins early in the \"scholler\" rank during the student's training with his/her participation in an existing or ongoing research project.";
$rnk_p22[0]	= "The designation <b>provost</b> is granted by the school's governing body and is achieved when the student has The International Masters at Arms Federationachieved the highest technical skill of a weapon and that a research project is completed along with a research paper submission. A <b>provost</b>, by definition is an individual who is the head or master of a particular college or subject. Using this definition with respect to martial arts would also include weapons skills, relevant techniques and their surrounding history. One can use the analogy that a <b>provost</b> has obtained a doctorate in this particular weapon's type. A <b>maestro</b> is one who has been granted this title by an external governing body or existing maestro.";
$rnk_p23[0]	= "One of the most important steps in the progression from the rank of <b>scholler</b> to <b>maestro</b> is the concept of \"prizes and challenges\". The quest for the prize of promotion is a fundamental cultural component of the Academy, in which most, if not all students desire to obtain the prize through a minimum of 3 challenges against individuals in the next rank desired for each weapon currently being trained in. The play for the prize is comprised of two steps. The first step occurs as an event internal to the Academy in which the student's skills are assessed in private by the AEMMA governing body. The second step is for the student to submit a challenge for the prize of <b>scholler</b>, however, no student is allowed to submit challenges until the private examination is complete and deemed successful. There is no real time span before the student can play for the prize once the challenge has been submitted, however, it is usually left up to the student. Only the <b>recruit</b> and <b>scholler</b> has this prize option in the promotion to <b>scholler</b> and <b>free scholler</b> rank respectively. Higher ranks prizes are governed on a time basis structure.";
$rnk_p24[0]	= "The expectation of training is that the student, with regular practice and commitment can achieve the highest ranking and competency level, maestro in approximately 5 to 10 years. This has great variations, depending upon the commitment of the student to training, attendance to classes, research project development, availability of the student to training, physical capabilties, stamina and their natural physical skills of the student. Skill and safety are paramount in the training program.";

$rnk_l1[0]	= "<i>Liber Albus</i> (White Book) contains the laws and customs of the city of London, compiled in 1419, by John Carpenter, common clerk.";
$rnk_l2[0]	= "Riley, H.T. (trans), 1861 <a href=\"https://archive.org/details/liberalbuswhiteb00carpuoft\" target=\"_blank\" title=\"The White Book\"><i>Liber Albus</i></a>";
$rnk_l3[0]	= "Brown, Terry. \"<a href=\"https://www.amazon.com/exec/obidos/ASIN/1898281181/academyofeuropea\" target=\"_blank\">English Martial Arts</a>\". 1997";


?>
