<?php
// Program: content_about_arms_en.php
//	Description: source for the English textual content on the about the armorial bearings page (about_arms.php)
//	2016 ------------------
//
// English content -------------------
$title[0] = "The Academy's Armorial Bearings (coat of arms)";
$aemma_arms_caption[0] = "The armorial bearings, banner and badge of the Academy of European Medieval Martial Arts.  The grant of arms were sourced from the Canadian Heraldic Authority in Ottawa on January 15, 2008. <sup><a href=\"#1\" title=\"Reference #1: grant of arms\">[1]</a></sup>";
$aemma_arms_evolution_caption[0] = "A depiction of the evolution of the arms of AEMMA since 1998 to the current grant of arms.";

$title_p1[0]	= "Symbolism & Heraldry in AEMMA";
$arms_p1_1[0]	= "Symbolism is the use of abstractions to represent and idea or concept. Heraldry is a form of symbolism, which concerns itself with the study, design, regulation and use of armorial bearings, commonly referred to as \"coats of arms\" <sup><a href=\"#2\" title=\"Reference #2: coat of arms\">[2]</a></sup> <sup><a href=\"#3\" title=\"Reference #3: coat of arms (Encyclopædia Britannica)\">[3]</a></sup>. A coat of arms is a form of personal or corporate identification of which the central element is a shield. Its roots began in the early 12th century, largely because of the development at that time of helmets that covered and concealed the face of the wearer. There is a strong connection between heraldry and knights of the period, which were and effective manner of identifying themselves by painting devices (charges or objects) on their shields, to wearing the same symbols on their surcoats worn over armour (hence the \"coat\" in \"coat of arms\") to the caparisons worn by their warhorses. ";
$arms_p1_2[0]	= "Arms (coats of arms) is an important part of the tradition at AEMMA, whereby, students having successfully achieved the rank of Scholar, are encouraged to contemplate their own personal coat of arms.  Assistance in its design and symbolism are provided by a number of members who possess experience in the field of heraldry.  Once the new scholar has completed their design, the arms are then painted on a wooden shield and are then suspended on the wall at the <i>salle d'armes</i>.  The arms suspended are in chronological order from the earliest students (David, Brian, etc.) to the most recent scholars.  The arms are also an important part of the Scholar and Free Scholar tests, as during the portion of the freeplay in the test, the candidate must combat all scholars and above attending the test.  The arms are a reference to all who participate in terms of the order in which they will combat the candidte. The candidate begins the challenges with the newest scholar to free scholars to ultimately, the Provosts of the Academy.";

$title_p2[0]	= "Evolution of AEMMA's Armorial Bearings";
$arms_p2_1[0]	= "From the early sketches of the arms by David in late 1997 to mid-1998, the consistent attributes of the arms included a single sword on the arms (the shield) and two supporting heraldic beasts, originally beginning with dragons. These arms continued to evolve whereby in later 1998, the first resemblance of the grant of arms appeared, with the purple chevron and a sword centrally positioned, with point upwards. Once the research and training regimine stablized on Fiore's works, the arms changed to reflect that new direction of the Academy, which began earlier in 2000. The heraldic beasts now appear on those arms, sourced from Fiore's \"sette spada\" folio.  The basic tinctures and charges on the arms stabilized with the chevron purpure on a shield Argent with sword proper pointing upwards. Later in 2002, the arms take on a closure rendering to the official grant of arms from 2007, which preserved the heraldic beasts from Fiore, changed the presentation of the motto and banner and the mound on which the supporters and arms stand. The arms are also visible on Canada's <a href=\"http://reg.gg.ca/heraldry/pub-reg/main.asp?lang=e\" target=\"_blank\" title=\"Public Register of Arms, Flags and Badges of Canada\">Public Register of Arms, Flags and Badges of Canada</a>  <sup><a href=\"#4\" title=\"Reference #4: Public Register of Arms, Flags and Badges of Canada\">[4]</a></sup>.";

$arms_l1[0]	= "<a href=\"http://www.gg.ca/document.aspx?id=2&lan=eng\" target=\"_blank\" title=\"The Canadian Heraldic Authority\">The Canadian Heraldic Authority</a> (CHA; French: <a href=\"http://www.gg.ca/document.aspx?id=2&lan=fra\" target=\"_blank\" title=\"L'Autorité héraldique du Canada\"><i>L'Autorité héraldique du Canada</i></a>) is part of the Canadian honours system under the Canadian monarch, whose authority is exercised by the Governor General of Canada. The authority is responsible for the creation and granting of new coats of arms (armorial bearings), flags, and badges for Canadian citizens and corporate bodies. The authority also registers existing armorial bearings granted by other recognized heraldic authorities, approves military badges, flags, and other insignia of the Canadian Forces, and provides information on heraldic practices.  The <a href=\"http://www.heraldry.ca\" target=\"_blank\" title=\"Royal Heraldry Society of Canada\">Royal Heraldry Society of Canada</a> was instrumental in the formation of the Canadian Heraldic Authority, which was established on June 4, 1988. Retrieved: April 21, 2016.";
$arms_l2[0]	= "A coat of arms is a unique heraldic design on an escutcheon (i.e. shield), surcoat, or tabard. The coat of arms on an escutcheon forms the central element of the full heraldic achievement which consists of shield, supporters, crest, and motto. The design is a symbol unique to an individual person or family (except in the UK), corporation, or state. source: Wikipedia. <a href=\"https://en.wikipedia.org/wiki/Coat_of_arms\" target=\"_blank\">Coat of arms</a>. Retrieved: January 17, 2017.";
$arms_l3[0]	= "Coat of arms, the principal part of a system of hereditary symbols dating back to early medieval Europe, used primarily to establish identity in battle. Arms evolved to denote family descent, adoption, alliance, property ownership, and, eventually, profession. source: Encyclopædia Britannica. <a href=\"=https://www.britannica.com/topic/coat-of-arms\" target=\"_blank\">Coat of arms - Heraldry</a>. Retrieved: January 17, 2017.";
$arms_l4[0]	= "The Public Register of Arms, Flags and Badges of Canada contains the heraldic emblems that have been granted, registered, approved or confirmed by the Canadian Heraldic Authority since its inception on June 4, 1988. In 2005, the Canadian Heraldic Authority began the process of creating a digital version of the register available online.";

?>
