<?php
// Program: content_about_arms_fr.php
//	Description: source for the textual content on the about the armorial bearings page (about_arms.php) (« »)
//	2016 ------------------
///
// French content -------------------
$title[1] = "Emblèmes héraldiques de l'Académie ( manteau des bras )";
$aemma_arms_caption[1] = "Les armoiries, bannière et l'insigne de l'Académie des européennes médiévales Arts Martiaux. La subvention des armes provenaient de l'Autorité héraldique du Canada, à Ottawa, le 15 Janvier 2008. <sup><a href=\"#1\" title=\"référence n° 1 : subvention d'armes\">[1]</a></sup>";
$aemma_arms_evolution_caption[1] = "Une représentation de l'évolution des armes de AEMAM depuis 1998 à la subvention actuelle des armes.";

$title_p1[1]	= "Symbolisme & Héraldique dans AEMAM";
$arms_p1_1[1]	= "Le symbolisme est l'utilisation des abstractions pour représenter et idée ou concept. Héraldique est une forme de symbolisme, qui se préoccupe de l' étude, la conception, la réglementation et l'utilisation des armoiries, communément appelé « armoiries » <sup><a href=\"#2\" title=\"référence n° 2 : armoiries\">[2]</a></sup> <sup><a href=\"#3\" title=\"référence n° 3 : référence (Encyclopædia Britannica)\">[3]</a></sup>. Un blason est une forme d'identification personnelle ou d'entreprise, dont l'élément central est un bouclier. Ses racines ont commencé au début du 12ème siècle, en grande partie en raison du développement à l'époque des casques qui couvrait et cachait le visage du porteur. Il y a un lien étroit entre l'héraldique et les chevaliers de l'époque, qui étaient et de manière efficace de s'identifier en peignant des dispositifs ( charges ou objets) sur leurs boucliers, à porter les mêmes symboles sur leurs surcoats portés sur l'armure (d'où le « manteau » dans « armoiries » ) aux caparaçons portés par leurs destriers.";
$arms_p1_2[1]	= "Arms (armoiries) est une partie importante de la tradition à AEMAM, grâce à quoi, les étudiants ayant réussi à atteindre le rang de Scholar, sont encouragés à envisager leur propre armoiries personnelles. Assistance dans sa conception et le symbolisme sont fournis par un certain nombre de membres qui possèdent une expérience dans le domaine de l'héraldique. Une fois que le nouveau chercheur a terminé leur conception, les bras sont ensuite peints sur un bouclier en bois et sont ensuite suspendues sur le mur à la salle d'armes. Les bras en suspension sont dans l'ordre chronologique des premiers étudiants (David, Brian, etc.) aux savants les plus récents. Les bras sont aussi une partie importante des essais Scholar et Scholar gratuit, comme lors de la partie du freeplay dans le test, le candidat doit lutter contre tous les chercheurs et surtout assister à l'épreuve. Les bras sont une référence à tous ceux qui participent en termes de l'ordre dans lequel ils vont combattre le candidte. Le candidat commence les défis avec le nouveau savant aux savants libres en fin de compte, les prévôts de l'Académie.";

$title_p2[1]	= "Evolution des emblèmes héraldiques de AEMAM";
$arms_p2_1[1]	= "Dès les premiers croquis des bras de David à la fin de 1997 à la mi-1998, les attributs constants des bras inclus une seule épée sur les bras (le bouclier) et deux à l'appui des bêtes héraldiques, en commençant à l'origine avec des dragons. Ces armes ont continué d'évoluer de sorte que plus tard 1998, la première ressemblance de l'octroi d'armes est apparu, avec la pourpre de chevron et une épée en position centrale, avec le point vers le haut. Une fois que le regimine de recherche et de formation stabilisé sur les travaux de Fiore, les bras modifiés pour refléter cette nouvelle direction de l'Académie, qui a commencé plus tôt en 2000. Les bêtes héraldiques apparaissent maintenant sur les bras, provenant de la Fiore <i>sette spada</i> folio. Les teintures et les frais de base sur les bras stabilisés avec le purpure chevron sur un bouclier d'argent de l'épée pointant correcte vers le haut. Plus tard, en 2002, les bras prennent une fermeture rendant à l'octroi officiel d'armes à partir de 2007, qui a conservé les bêtes héraldiques de Fiore, a modifié la présentation de la devise et la bannière et le monticule sur lequel les partisans et les bras se tiennent. Les bras sont également visibles sur Canada's <a href=\"http://reg.gg.ca/heraldry/pub-reg/main.asp?lang=f\" target=\"_blank\" title=\"Le Registre public des armoiries, drapeaux et insignes du Canada\">Le Registre public des armoiries, drapeaux et insignes du Canada</a> <sup><a href=\"#4\" title=\"référence n° 4 :Registre public des armoiries, drapeaux et insignes\">[4]</a></sup>.";

$arms_l1[1]	= "<a name=\"1\"></a><a href=\"http://www.gg.ca/document.aspx?id=2&lan=fra\" target=\"_blank\" title=\"L'Autorité héraldique du Canada\"><i>L'Autorité héraldique du Canada</i></a> ( AHC; anglais : <i><a href=\"http://www.gg.ca/document.aspx?id=2&lan=eng\" target=\"_blank\" title=\"The Canadian Heraldic Authority\">The Canadian Heraldic Authority</a></i> ) fait partie du système canadien de distinctions honorifiques dans le monarque du Canada , dont l'autorité est exercée par le gouverneur général du Canada . L'autorité est responsable de la création et de l'octroi de nouvelles armoiries (les armoiries ) , drapeaux et insignes pour les citoyens et les organismes canadiens . L'autorité enregistre également les armoiries existantes accordées par d'autres autorités héraldiques reconnues , approuve les insignes militaires , drapeaux et autres insignes des Forces canadiennes , et fournit des informations sur les pratiques héraldiques. Le <a href=\"http://www.heraldry.ca\" target=\"_blank\" title=\"Société royale héraldique du Canada\">Société royale héraldique du Canada</a> a joué un rôle dans la formation de l'Autorité héraldique du Canada, qui a été créé le 4 juin 1988. consulté le : 21 avril 2016.";
$arms_l2[1]	= "Un blason est un dessin héraldique unique sur un écusson (c'est-à-dire le bouclier), surcoat, ou tabard. Les armoiries sur un écusson forment l'élément central de la pleine réalisation héraldique qui consiste en bouclier, partisans, crête et devise. La conception est un symbole unique à une personne ou une famille (sauf au Royaume-Uni), une société ou un état. source : Wikipedia. <a href=\"https://fr.wikipedia.org/wiki/Blason_(h%C3%A9raldique)\" target=\"_blank\">Blason (héraldique)</a>. consulté le : 17 janvier 2017.";
$arms_l3[1]	= "Armoiries, la partie principale d'un système de symboles héréditaires datant de l'Europe du début du Moyen-âge, utilisé principalement pour établir l'identité dans la bataille. Les bras ont évolué pour désigner la descendance de la famille, l'adoption, l'alliance, la propriété et, finalement, la profession. source : Encyclopædia Britannica. <a href=\"=https://www.britannica.com/topic/coat-of-arms\" target=\"_blank\">Coat of arms - Heraldry</a>.consulté le : 17 janvier 2017.";
$arms_l4[1]	= "Le Registre public des armoiries, des drapeaux et des insignes du Canada contient les emblèmes héraldiques qui ont été accordés, enregistrés, approuvés ou confirmés par l'Autorité héraldique du Canada depuis sa création le 4 juin 1988. En 2005, l'Autorité héraldique du Canada a entamé le processus La création d'une version numérique du registre disponible en ligne.";
?>
