<?php
// Program: content_about_about_en.php
//	Description: source for the English textual content on the about the AEMMA page (about_about.php)
//	2016 ------------------
//
// English content -------------------
$title[0] = "About the Academy of European Medieval Martial Arts (AEMMA)";
$about_aemma_arms_caption[0] = "The armorial bearings of the Academy of European Medieval Martial Arts";
$about_pas_d_armes_caption[0] = "One of numerous <i>pas d'armes</i> organized and/or hosted by AEMMA. This one held on April 25, 2010. The combatant on the left is Matt McKee from the Ottawa Medieval Swordplay Guild, and the combatant on the right is Aldo Valente of AEMMA. Photo courtesy of Emily Tanaka. ";
$about_unarmoured_tourney_caption[0] = "A shot of one of many unarmoured tournaments (November 7, 2009) hosted by AEMMA at the <i>salle d'armes</i>. On the left, Provost David M. Cvet observes the combatants with a watchful eye. The left combatant is David B. Murphy, and his opponent is Aaron Bolarinho. Photo courtesy of Emily Tanaka.";

$title_p1[0]	= "What is AEMMA?";
$about_p1_1[0]	= "The <b>Academy of European Medieval Martial Arts</b> or <b>AEMMA</b> (pronounced \"<b>ehma</b>\") is focused on the research, reconstruction and resurrection of authentic mediaeval combative systems (armed, unarmed, armoured and unarmoured), firmly based on the works of the late 14th century Friulian swordsmaster by the name of Fiore dei Liberi, demonstrating the deadly practicality and effectiveness of the art as it applies to today's personal self-defense.";
$about_p1_2[0]	= "AEMMA was initially created in May of 1998 in <a href=\"http://www.toronto.com\" target=\"_blank\" title=\"Toronto, Ontario, Canada\"><b>Toronto</b></a> and under the laws of Ontario's Corporations Act and the Regulations of the Ministry of the Attorney General, was incorporated as a not-for-profit corporation (NPO Corporation Number: 1468524) in May 28, 2001. It has as its mission:
<blockquote><font color=\"#461B7E\"><i>The mission of AEMMA is to resurrect, research, study, practice and instruct in the combat skills, philosophies and principles of accomplished European Mediaeval martial artists and to achieve a state which would be consistent with that of a mediaeval combatant in both technology and ideal.</i></font></blockquote>";
$about_p1_3[0] = "In order to satisfy the mission, AEMMA is dedicated to the research, study, reconstruction and practice of early period martial arts in all aspects with respect to arms and armour, technical skills, combative theory and the relevant philosophies and principles as they relate to these fighting arts.  In order to satisfy this mission, AEMMA has these goals: 
<blockquote><ol><li>research and study historical sources in the form of treatises, manuscripts, illuminations, etc. as well as the physical examination of artifacts from the period including arms and armour accessed through the <a href=\"http://www.rom.on.ca\" target=\"_blank\" title=\"Royal Ontario Museum\">Royal Ontario Museum</a> (ROM) in order to facilitate accurate resurrecting and reconstructing the mediaeval fighting arts;<br />&nbsp;</li><li>to provide a training and research environment to permit the application of research into practice and their later inclusion into the relevant training programs, and to enable the instruction and training of these fighting arts in order to develop the students' personal defensive and offensive skills.</li>
</ol></blockquote>";

$title_p2[0]	= "The Vision";
$about_p2_1[0]	= "It is the desire and ambition of AEMMA to establish a leading academy in the research, training and instruction of mediaeval martial arts by creating a viable and sustainable environment in which to develop and evolve the mediaeval martial arts system known as <b><i>l&#180;arte dell&#180;armizare</i></b> <sup><a href=\"#1\" title=\"Reference #1: armizare\">[1]</a></sup> or the 'art of fighting'.  This form of martial arts falls into a category commonly referred to has Historical European Martial Arts or HEMA <sup><a href=\"#2\" title=\"Reference #2: HEMA\">[2]</a></sup> <sup><a href=\"#3\" title=\"Reference #3: HEMAC\">[3]</a></sup>. The intention is to offer to its students, an alternative training system to the popular martial arts systems available today by being able to provide all of the expected benefits of martial arts training in terms of self-defense, fitness and offensive skills while learning and training in <b><i>l&#180;arte dell&#180;armizare</i></b>";
$about_p2_2[0]	= "In conjunction with this ambition, AEMMA will further its mission through education and programming designed to enhance the students' experience and appreciation of the fighting art through events such as armoured tournaments or <a href=\"../index2.php?pg=t6\" target=\"_top\"><i>pas d'armes</i></a> <sup><a href=\"#4\" title=\"Reference #4: pas d'armes\">[4]</a></sup>, <a href=\"../index2.php?pg=t7\" target=\"_top\">judicial duels/trial by combat</a>, <a href=\"../index2.php?pg=t8\" target=\"_blank\">unarmoured tournaments</a> and other aspects of the period including the study and application of heraldry.  These events are intended to not only educate the students of the Academy, but also to educate and enhance the experience of the public in these particular aspects of the mediaeval period.";

$about_l1[0]	= "The name <a href=\"glossary.html#armizare\"><i>l&#180;arte dell&#180;armizare</i></a> or simply <a href=\"glossary.html#armizare\"><i>armizare</i></a> identifies this particular form of <a href=\"glossary.html#tma\">Historical European Martial Art</a> (HEMA), which is based on the tradition of <a href=\"../onlineResources/liberi/liberiHome.htm\">Fiore dei Liberi</a>.  In at least five versions of the Liberi treatise, the versions studied at AEMMA are referred to as:
<ul><li>Getty: \"<i>armi&ccedil;are arte de combatter</i>\"</li><li>Morgan: \"<i>armizare e arte de combater</i>\"</li><li>Pisani-Dossi: \"<i>armi&ccedil;ar e de combatere</i>\"</li>
</ul>The term <i>armizare</i> is derived from the above examples, and is felt that it uniquely identifies this art.  Liberi in his texts would often refer to this as simply \"the art\".";
$about_l2[0]	= "Historical European martial arts (HEMA) refers to martial arts of European origin, particularly using arts formerly practised, but having since died out or evolved into very different forms. The term Western martial arts (WMA) is sometimes used in the United States and in a wider sense including modern and traditional disciplines. During the Late Middle Ages, the longsword had a position of honour among these disciplines, and sometimes historical European swordsmanship (HES) is used to refer to swordsmanship techniques specifically. source: Wikipedia. <a href=\"https://en.wikipedia.org/wiki/Historical_European_martial_arts\" target=\"_blank\">Historical European martial arts</a>. Retrieved: January 17, 2017.";
$about_l3[0]	= "The Historical European Martial Arts Coalition (HEMAC) is a collection of martial artists and researchers in Europe.  They are dedicated to the study, reconstruction, practice and promotion of traditional European fighting arts, based on the study of surviving technical sources (treatises and manuals). HEMAC was established in 2001 and is a non-hierarchical, round-table organisation, consisting of individual researchers and martial artists from many groups across Europe. source: <a href=\"http://www.hemac.org/\" target=\"_blank\">HEMAC</a>. Retrieved: January 17, 2017.";
$about_l4[0]	= "The <i>pas d'armes</i> or the \"Passage of arms\", refers to a particular type of \"competitive\" armoured bouts, and narrows its meaning to describe a series of \"combats on foot\", each bout being defined in terms of weapon or weapons as selected by the appellants or venans (the visiting team), for his/her challenge, and limited to three to five decisive blows or three minute time limit. Further information can be perused on: source: Wikipedia. <a href=\"https://en.wikipedia.org/wiki/Pas_d%27armes\" target=\"_blank\">Pas d'armes</a>. Retrieved: January 17, 2017.";
?>
