<?php
// Program: content_rnk_scholler_en.php
//	Description: source for the English textual content on the rank of scholler page (rnk_scholler.php)
//	2017 ------------------
//
// English content -------------------
$title[0] 	= "Rank: Scholler";
$banner[0] 	= "<img src=\"../images/banner_scholler.jpg\" alt=\"\" width=\"100%\"/>";
$rnk_p11[0]	= "The rank of <b>scholler</b> identifies a student and practitioner of the historal European martial arts known as <i><b>l`arte dell`armizare</b></i> or simply as <b><i>armizare</i></b> and is one who has committed to learning and training in the art. The <b>scholler</b> recognizes that in order to become proficient in this art, as with any other martial arts systems, it is a life-style choice requiring the commitment and dedication necessary to achieve a level of excellence that will enrich the student's life both intellectually and physically. In order to achieve competency in the more advanced levels, the scholler must attempt to schedule him/herself accordingly to permit attending regular training sessions. The <b>scholler</b> must abide by the rules and constitution of the Academy, and be prepared to obtain the relevant historically accurate arms & armour for those weapons trained with. <b>Scholler</b> training is the longest and most intense of all the ranks.";
$rnk_p12[0]	= "It is during the <b>scholler</b> training where the student learns how to \"fight\" becoming both a knowledgable, skillful and competent martial artist.  The foundational principles learned and trained during the recruit training forms the basis on which advanced techniques and combative principles are built upon.  The training structure mirrors the format of Fiore dei Liberi's <a href=\"\" target=\"_top\"><i>Flos Duellatorum</i></a> in terms of training segments mapping to the fighting/weapons styles documented in the treatise.  The scholler will continue to train in the core training components (<i>abrazare, daga, spada</i>) of the recruit training program, but will delve into these segments in far greater depth.  These segments will be scheduled throughout the year, so that over time, a scholler will have the opportunity to train, practice and be tested in each of the segments. ";
$rnk_p13[0]	= "The scholler training program will encompass the following styles: <i>abrazare, daga, spada, spada e brocchiere, spada longa</i>, poleweapons: <i>azza e lanza</i>, and <i>arme</i> not necessarily in that order. <b>At the conclusion of the program, the scholler is tested by the instructors.</b>  If the scholler passes the <b>scholler test</b>, he/she will be awarded a rondel dagger representing the prize successfully completed. This rondel dagger can be worn by the scholler during training and events.";
$rnk_p14[0]	= "From a heraldic perspective, <b>schollers</b> are encouraged to become  \"<b>invested with arms</b>\" so that their coats of arms can be suspended on display on the armory rack at the salle d'armes to which the schollar badges can be attached represented the segments successfully completed, and in the form of flags or banners during their participation in tournaments (armoured and/or unarmoured) or other events if appropriate.  For examples of arms currently possessed by schollers and above, click <a href=\"\"><b>here</b></a>. There are a number of resources to assist in this matter, and it is imperative that the arms created, assumed, matriculated, registered, granted is heraldically correct and therefore, to that end, there are a good number of individuals in AEMMA that can offer assistance and guidance. Further information can be found at the bottom of this (<b>scholler</b>) section by clicking <a href=\"\"><b>here</b></a>.";

$title_p2[0] 	= "Scholler Requirements";
$rnk_l21[0]	= "has obtained the rank of <b>scholler</b> by successfully challenging and completing the <font color=\"#461B7E\"><b>scholler test</b></font>,";
$rnk_l22[0]	= "<a href=\"\">training dues</a> are paid for on a regular basis and there are no outstanding dues,";
$rnk_l23[0]	= "possesses the <a href=\"\">minimum equipment</a> as required for the <b>scholler</b> rank,";
$rnk_l24[0]	= "has taken the initiative with respect to being \"invested with arms\" which have been approved by AEMMA or <a href=\"http://www.gg.ca/heraldry\" target=\"_blank\">CHA</a>, click <a href=\"#heraldry\"><img src=\"../images/coatofarms/tinyShield.gif\" valign=\"middle\" hspace=\"4\" border=\"0\" alt=\"\" class=\"fade\" title=\"Click to learn more about obtaining a personal coat of arms\"></a> for more info.";

?>
