<?php
// Program: content_rnk_recruit_fr.php
//	Description: source for the textual content on the rank of recruit page (rnk_recruit.php) (« »)
//	2017 ------------------
///
// French content -------------------
$title[1] 	= "Rang: Recruit";
$banner[1] 	= "<img src=\"../images/banner_recruit.jpg\" alt=\"\" width=\"100%\" />";
$rnk_p11[1]	= "Le rang de recruteur identifie un élève de niveau d'entrée de l'art martial connu sous le nom de <b><i>l`arte dell`armizare</i></b> ou simplement comme <b><i>armizare</i></b>. Un étudiant nouvellement inscrit qui commence sa formation à AEMAM, est informé avec un aperçu de l'Académie, le personnel clé, et donne un aperçu du programme de formation, de sa structure et de sa durée. Le <b>recrutement</b> commence par recevoir des instructions sur les fondements d'<i>abrazare</i> (se battant), <i>daga</i> (poignard) et <i>spada</i> (épée) basé sur <a href=\"about_schedule.php\" target=\"_top\" title=\"cliquez pour consulter le calendrier de formation\"> programme de formation </a>.";
$rnk_p12[1]	= "En tant que nouveau <b>recruteur</b>, l'élève a la possibilité d'évaluer s'il faut ou non poursuivre cette forme d'art martial avec un engagement de niveau compatible avec son style de vie et ses engagements actuels. Au cours de cette période d'essai, recruter des exigences d'équipement de formation pour commencer la formation entraîne un coût modeste qui englobe l'achat d'un t-shirt d'entraînement AEMAM, de gants de jardin-variété en cuir, de jambières / pantalons noirs et de chaussures de course à semelles plates confortables (dont certaines peut déjà être en possession du nouvel étudiant).";
$rnk_p13[1]	= "Après une période de formation, qui peut prendre de 8 mois à 2 ans ou plus, le recruteur peut être prêt à défier pour le rang de <a href=\"rnk_scholler.php\" target=\"_ top\" title=\"Cliquez pour lire le rang d'informations scholler\">scholler</a>. À ce stade de la formation de recrutement, l'étudiant ne devrait pas se considérer comme un combattant tout à l'heure, cependant, il possédera les compétences fondamentales nécessaires pour développer et développer ces compétences dans des techniques de combat sophistiquées dans <a href=\"rnk_scholler.php\" target=\"_ top\" title=\"cliquez pour parcourir le classement de l'information scolaire\">scholler</a> niveau de formation et sera en mesure de déployer quelques manœuvres de défense de base si nécessaire si Une opportunité se présente. Après avoir terminé la formation de recrutement, le programme est conçu de manière à ce que l'élève soit en mesure de se disputer pour le prix de <a href=\"rnk_scholler.php\" target=\"_ top\" title=\"click Pour lire le classement de l'information de scholler\">scholler</a> en passant par un public <a href=\"\" target=\"_top\" title=\"click pour examiner un exemple de test de scholler \">test de scholler</a> en présence des pairs de l'élève. Bien sûr, à ce stade de la formation du recruteur, d'autres <a href=\"\" target=\"_top\" title=\"click pour consulter les détails sur l'équipement de formation scholler\">équipement de formation scholler</a > Aurait été acheté, car il s'agit d'une autre exigence pour un défi pour le <a href=\"rnk_scholler.php\" target=\"_top\" title=\"click pour lire le rang de l'information scholler\">scholler</a> rang.";

$title_p2[1] 	= "Exigences de recrutement";
$rnk_l21[1]	= "aucune expérience antérieure en formation sur les arts martiaux nécessaire,";
$rnk_l22[1]	= "doit être de 18 ans ou plus <i>(les candidats de moins de 18 ans doivent être accompagnés par un tuteur pour signer les formulaires pertinents et sont interviewés par le ou les instructeurs pour déterminer si le candidat est suffisamment mature pour s'entraîner)</i>,";
$rnk_l23[1]	= "Formulaires administratifs complets qui comprennent la demande d'adhésion et le formulaire de renonciation individuelle fournis par l'un des agents,";
$rnk_l24[1]	= "la candidature a été approuvée et acceptée par l'Académie,";
$rnk_l25[1]	= "une photo du recruteur pris par un membre de l'AEMAM ou transmise à AEMAM au format jpg / png, pour l'inclusion du dossier de formation du recruteur dans la base de données de formation de membre de l'AEMAM (utilisé en interne par les instructeurs uniquement),";
$rnk_l26[1]	= "<a href=\"about_fees.php\" title=\"cliquez pour lire les détails des frais de formation\" target=\"_top\">frais de formation</a> sont payés régulièrement et il n'y a pas de cotisation exceptionnelle,";
$rnk_l27[1]	= "click ==> <a href=\"\" title=\"cliquez pour examiner les besoins en équipement de recrutement\" target=\"_top\">exigences d'équipement</a> pour des détails et des descriptions sur les exigences minimales en matière d'équipement de recrutement,";
$rnk_l28[1]	= "le recruteur a lu, compris et conforme à la <a href=\"about_rules.php\" title=\"cliquez pour lire les règles de la Salle\" target=\"_top\">Règles de la Salle d'Armes</a>.";
?>
