<?php
// Program: content_arte_fiore_dei_liberi_en.php
//	Description: source for the French textual content for the overview of Fiore dei Liberi (arte_fiore_dei_liberi.php) (« »)
//	2017 ------------------
//
// French content -------------------
$title[1] = "À propos de Maestro Fiore dei Liberi";
$arte_fiore_dei_liberi_caption[1] = "Une image de la première page du prologue trouvée dans la version Pisani-Dossi de Flos Duellatorum. Cliquer pour agrandir l'image du prologue.";
$arte_fiore_dei_liberi_prologue_title[1] = "Cliquer pour agrandir l'image du prologue.";
$arte_premariacco_caption[1] = "Les armoiries du village de Premariacco. Premariacco est une commune italienne de la province de Udine dans la région Frioul-Vénétie julienne en Italie.";
$arte_premariacco_title[1] = "Cliquez pour visiter la communauté du site de Premariacco";
$arte_p1[1] = "En dépit de l'impact significatif que le traité de Fiore a eu sur la reconstruction moderne des arts de combat historiques, en particulier, armizare, très peu est connu de l'homme qui portait le nom de Fiore dei Liberi. Jusqu'à présent, étant donné la vaste et continue recherche menée dans le monde entier par une variété d'écoles et d'académies d'escrime historiques la seule source définitive pour la biographie de Fiore a été le prologue écrit par Fiore lui-même contenu dans trois versions du traité. ";
$arte_p2[1] = "Le traité, écrit par Fiore lui-même, se \"<i>Fior Furlan de Ciuida dostria</i> \" dans le prologue de Getty <sup><a href=\"#1\" title=\"référence n° 1: Getty\">[1]</a></sup>, \"<i>Fiore Furlan de Ciuida dostria</i> \" dans la version de Morgan <sup><a href=\"#2\" title=\"référence n° 2 : Morgan\">[2]</a></sup> and \"<i>Fior furlano dei liberi de Ciuidal dostria</i> \" dans l' \"<i>alter prologus</i> \" dans la version Pisani-Dossi (PD) <sup><a href=\"#3\" title=\"référence n° 3 : Pisani Dossi\">[3]</a></sup>. La phrase PD se traduit par \"Fiore Friuli de la famille du Liberi de Cividale d'Austria\" qui est communément abrégé \"<i>Fiore dei Liberi</i> \". Le prologue nous dit que Cividale d'Autriche faisait partie du diocèse d'Aquileia et qu'il était né le fils de \"<i>meser benedetto de la casada dei liberi da premergiago</i> \" traduit comme \"Sir Benedetto de la Maison du Liberi de Premariacco\". Le village de Premariacco <sup><a href=\"#4\" title=\"référence n° 4 : Premariacco\">[4]</a></sup> et Cividale d'Austria (maintenant Cividale del Friuli) existe aujourd'hui et réside dans une zone connue sous le nom de \"Friuli\", une zone avec sa propre identité culturelle et historique unique. Cividale del Friuli est la dernière résidence connue de Fiore basée sur les extraits des prologues. ";
$arte_p3[1] = "Fiore ne révèle pas sa date de naissance ni l'année dans aucune version du traité, cependant, on estime que Fiore est né vers 1350. Cette année estimée devient plus évidente après un examen plus approfondi du texte extrait du prologue. Il a écrit qu'il avait une capacité combative naturelle à un jeune âge, ayant quitté son village de Premariacco pour apprendre des techniques plus avancées d'escrime et d'augmenter ses compétences en voyageant dans de nombreuses provinces, la formation sous de nombreux maîtres italiens et allemands. Il a déclaré qu'il s'entraînait et se battait depuis plus de 40 ans, et étant donné le moment où il a commencé à écrire le traité le 10 février 1409 et l'hypothèse qu'il a commencé la formation et l'escrime à l'âge de 10 ans, Environ soixante ans au moment de la rédaction du traité. ";
$arte_p4[1] = "Sans aucun doute, la partie la plus pénible de la vie de Fiore fut ses dernières années, à la fin du XIVe siècle et au début du XVe siècle pendant la période de la composition de son traité ou de ses traités. La version Pisani-Dossi met en évidence Nicolo III d'Este et Marquis de Ferrare et mentionne que la composition du traité comprenant à la fois l'écriture et les illustrations était à la demande de Nicolo. Cela implique que Nicolo était Patron de Fiore et a donc commandé à Fiore de composer un livre sur le combat pour satisfaire le désir de Nicolo d'ajouter à sa vaste collection bibliographique. Il n'y a rien dans le prologue qui puisse indiquer que Fiore était un membre de la cour du marquis et donné à Fiore était un épée réputé et notable, la bibliothèque de Nicolo a été augmentée avec l'addition du traité de Fiore qu'il a commencé à écrire le 10 février 1409 et a terminé le Six mois plus tard.";

$arte_l1[1] = "<b><i>Fior di Battaglia</b></i>: MS Ludwig XV 13 - <a href=\"http://www.getty.edu/art/collection/objects/1443/unknown-fiore-furlan-dei-liberi-da-premariacco-il-fior-di-battaglia-italian-about-1410/\" target=\"_blank\" title=\"J. Paul Getty Museum (codice 'GETTY')\">J. Paul Getty Museum (codice \"GETTY\")</a>";
$arte_l2[1] = "<b><i>Fior di Battaglia</b></i>: MS M.383 - <a href=\"http://ica.themorgan.org/manuscript/page/1/77302\" target=\"_blank\" title=\"The Pierpoint Morgan Library (codice 'MORGAN')\">The Pierpoint Morgan Library (codice \"MORGAN\")</a>";
$arte_l3[1] = "<b><i>Flos Duellatorum (Pisani-Dossi MS)</b></i>: <a href=\"http://wiktenauer.com/wiki/Flos_Duellatorum_(Pisani_Dossi_MS)\" target=\"_blank\" title=\"Pisani-Dossi MS (codice 'Pisani-Dossi MS')\">F. Novati, Flos duellatorum</a>: Il Fior di battaglia di maestro Fiore dei Liberi da Premariacco (Bergamo, 1902)";
$arte_l4[1] = "Premariac est une commune italienne de la province de Udine dans la région Frioul-Vénétie julienne en Italie. La région est située dans la province de Frioul-Vénétie julienne, dans la région Frioul-Vénétie Julienne. Premariacco frontières les municipalités suivantes: Buttrio, Cividale del Friuli, Corno di Rosazzo, Manzano, Moimacco, Pradamano, Remanzacco. Paulin II d'Aquileia, le patriarche d'Aquileia et l'un des plus éminents érudits de la Renaissance carolingienne, a été établi à Premariacco vers 726. source : Wikipedia. <a href=\"https://fr.wikipedia.org/wiki/Premariacco\" target=\"_blank\">Premariacco</a>. consulté le : 17 janvier 2017.";

?>
