<?php
// Program: content_about_about_fr.php
//	Description: source for the textual content on the about the AEMAM page (about_about.php) (« »)
//	2016 ------------------
///
// French content -------------------
$title[1] = "A propos de l'Académie de l'Europe médiévale Arts Martiaux (AEMAM)";
$about_AEMAM_arms_caption[1] = "Les armoiries de l'Académie de l'Europe médiévale Arts Martiaux";
$about_pas_d_armes_caption[1] = "L'un des nombreux « pas d'armes » organisé et / ou hébergé par AEMAM. Celui-ci a eu lieu le 25 avril 2010. Le combattant sur ​​la gauche est Matt McKee du Ottawa Medieval Swordplay Guild, et le combattant sur ​​la droite est Aldo Valente de AEMAM. Photo gracieuseté de Emily Tanaka. ";
$about_unarmoured_tourney_caption[1] = "Un tir de l'un des nombreux tournois non blindés (7 novembre, 2009) organisé par AEMAM au « salle d' armes » . Sur la gauche, Provost David M. Cvet observe les combattants avec un œil vigilant. Le combattant gauche est David B. Murphy, et son adversaire est Aaron Bolarinho. Photo gracieuseté de Emily Tanaka.";

$title_p1[1]	= "Qu'est-ce que AEMAM?";
$about_p1_1[1]	= "Le <b>Académie de l'Europe médiévale Arts martiaux</b > ou <b>AEMAM</b> (prononcé « <b>ehma</b> » ) se concentre sur la recherche, la reconstruction et de la résurrection de l'authentique médiévale systèmes de combat ( armés, non armés, blindés et non blindés ), fermement sur ​​la base des travaux de la swordsmaster frioulan fin du 14ème siècle par le nom de Fiore dei Liberi, ce qui démontre le caractère pratique mortelle et l'efficacité de l'art tel qu'il s'applique à l'auto- défense personnelle d'aujourd'hui.";
$about_p1_2[1]	= "AEMAM a été initialement créé en mai 1998 en <a href=\"http://www.toronto.com\" target=\"_blank\" title=\"Toronto, Ontario, Canada\"><b>Toronto</b></a> et en vertu des lois de Loi sur les sociétés de l'Ontario et les règlements du ministère du procureur général, a été constituée en tant que ( Nombre NPO Corporation : 1468524 ) sans but lucratif sur les sociétés au 28 mai 2001. Il a pour mission :
<blockquote><font color=\"#461B7E\"><i>La mission de AEMAM est de ressusciter, de la recherche, l'étude, la pratique et instruire dans les compétences de combat, les philosophies et les principes des arts martiaux médiévaux européens accomplis et d'atteindre un état qui serait conforme à celle d'un combattant médiéval dans la technologie et idéal.</i></font></blockquote>";
$about_p1_3[1] = "Afin de satisfaire la mission , AEMAM est dédié à la recherche, l'étude, la reconstruction et la pratique de la première période d'arts martiaux dans tous les aspects en ce qui concerne les armes et armures, compétences techniques, la théorie combative et les philosophies et principes pertinents qui ont trait à ces arts de combat. Afin de satisfaire cette mission , AEMAM a ces objectifs : 
<blockquote><ol><li>la recherche et l'étude des sources historiques sous la forme de traités , manuscrits, enluminures , etc., ainsi que l'examen physique des artefacts de la période, y compris les armes et armures accessible par le <a href=\"http://www.rom.on.ca\" target=\"_blank\" title=\"Royal Ontario Museum\"><i>Royal Ontario Museum</i></a> (ROM) afin de faciliter ressusciter précis et reconstruire les arts de combat médiéval;<br />&nbsp;</li><li>de fournir un environnement de formation et de recherche pour permettre l'application de la recherche dans la pratique et de leur inclusion ultérieure dans les programmes de formation pertinents, et pour permettre à l'instruction et à la formation de ces arts de combat afin de développer des compétences défensives et offensives personnelles des élèves.</li></ol></blockquote>";

$title_p2[1]	= "La vision";
$about_p2_1[1]	= "Il est le désir et l'ambition de AEMAM d'établir une académie de premier plan dans la recherche, la formation et l'enseignement des arts martiaux médiévaux en créant un environnement viable et durable qui permet de développer et de faire évoluer le système d'arts martiaux médiéval connu sous le nom <b><i>l&#180;arte dell&#180;armizare</i></b> <sup><a href=\"#1\" title=\"référence n° 1 : armizare\">[1]</a></sup> ou « art du combat ». Cette forme d'arts martiaux tombe dans une catégorie communément appelée a les Arts martiaux historiques européens ou HEMA <sup><a href=\"#2\" title=\"reference n° 2 : HEMA\">[2]</a></sup> <sup><a href=\"#3\" title=\"reference n° 3 : HEMAC\">[3]</a></sup> L'intention est d'offrir à ses étudiants, un système de formation alternative aux systèmes disponibles aujourd'hui les plus populaires d'arts martiaux en étant en mesure de fournir tous les avantages attendus de la formation d'arts martiaux en termes d'auto - défense, la condition physique et les compétences offensives tout en apprenant et de la formation dans <b><i>l&#180;arte dell&#180;armizare</i></b>";
$about_p2_2[1]	= "En conjonction avec cette ambition, AEMAM va poursuivre sa mission par l'éducation et des programmes conçus pour améliorer l'expérience et l'appréciation des étudiants de l' art de combat à travers des événements comme des tournois blindés ou <a href=\"../index2.php?pg=t6\" target=\"_top\"><i>pas d'armes</i></a> <sup><a href=\"#4\" title=\"référence n° 4 : pas d'armes\">[4]</a></sup>, <a href=\"../index2.php?pg=t7\" target=\"_top\">duels judiciaires / combat judiciaire</a>, <a href=\"../index2.php?pg=t8\" target=\"_blank\">tournois non blindés</a> et d'autres aspects de la période, y compris l'étude et l'application de l'héraldique. Ces événements sont destinés à éduquer non seulement les étudiants de l'Académie, mais aussi d'éduquer et d'améliorer l'expérience du public dans ces aspects particuliers de la période médiévale.";

$about_l1[1]	= "<a name=\"1\"></a>Le nom <a href=\"glossary.html#armizare\"><i>l&#180;arte dell&#180;armizare</i></a> ou simplement <a href=\"glossary.html#armizare\"><i>armizare</i></a> identifie cette forme particulière de <a href=\"glossary.html#tma\"><i>Historical European Art Martial</i></a> (HEMA), qui est basé sur la tradition <a href=\"../onlineResources/liberi/liberiHome.htm\">Fiore dei Liberi</a>.  Dans au moins cinq versions du traité Liberi , les versions étudiées à AEMAM sont appelés :
<ul><li>Getty: \"<i>armi&ccedil;are arte de combatter</i>\"</li><li>Morgan: \"<i>armizare e arte de combater</i>\"</li><li>Pisani-Dossi: \"<i>armi&ccedil;ar e de combatere</i>\"</li>
</ul>Le terme <i>armizare</i> est dérivé des exemples ci-dessus , et il est estimé qu'il identifie de façon unique cet art . Liberi dans ses textes se réfèrent souvent à ce que tout simplement «&nbsp;l'art&nbsp;».";
$about_l2[1]	= "Les arts martiaux européens historiques (HEMA) se réfèrent aux arts martiaux d'origine européenne, en particulier en utilisant des arts autrefois pratiqués, mais ayant depuis disparu ou évolué dans des formes très différentes. Le terme arts martiaux occidentaux (WMA) est parfois utilisé aux États-Unis et dans un sens plus large incluant les disciplines modernes et traditionnelles. À la fin du Moyen Âge, la longue épée avait une position d'honneur parmi ces disciplines, et parfois l'épée européenne historique (HES) est utilisé pour se référer spécifiquement aux techniques d'épée. la source : Wikipedia. <a href=\"https://fr.wikipedia.org/wiki/Arts_martiaux_historiques_europ%C3%A9ens\" target=\"_blank\">Les Arts martiaux historiques européens</a>. Dernier accès : 17 janvier, 2017.";
$about_l3[1]	= "La Coalition historique des arts martiaux européens (HEMAC) est une collection d'artistes et de chercheurs martiaux en Europe. Ils se consacrent à l'étude, à la reconstruction, à la pratique et à la promotion des arts de combat européens traditionnels, sur la base de l'étude des sources techniques survivantes (traités et manuels). HEMAC a été créé en 2001 et est une organisation non hiérarchique, de tables rondes, composée de chercheurs individuels et d'artistes martiaux de nombreux groupes à travers l'Europe. source : <a href=\"http://www.hemac.org/\" target=\"_blank\">HEMAC</a>. Dernier accès : 17 janvier, 2017.";
$about_l4[1]	= "Le <i>pas d'armes</i> ou la « <i>Passage of arms</i> » , fait référence à un type particulier de « compétitifs » combats blindés et rétrécit son sens pour décrire une série de « combats à pied » , chaque combat étant défini en termes d'arme ou des armes sélectionnées par les appelants ou venans ( la équipe visiteuse ), pour son / son défi, et limité à trois à cinq coups décisifs ou trois limite de temps de minute. Des informations supplémentaires peuvent être consultées : Wikipedia. <a href=\"https://fr.wikipedia.org/wiki/Pas_d%27armes\" target=\"_blank\">Pas d'armes</a>. Dernier accès : 17 janvier, 2017.";
?>
