<?php
// Program: content_about_new_fr.php
//	Description: source for the textual content on the new to this page (about_new.php) (« »)
//	2017 ------------------
//	jan 15:	introductory course fee is set in config.php, a single variable to ease on maintenance
//	jun 28:	PHP config variables $intro_armizare_start_time[1] and $intro_armizare_end_time[1] were added to the central config.php(fee there too)
///
// French content -------------------
if (isset($_GET['MNU'])) { $title[1] = "Introduction à l`arte dell`armizare (Armizare)"; } else { $title[1] = "Nouveau à cela? Commencer ici...";}
$new_red[1] = "nouveau.png";
$new_1_p1[1]	= "L'<b>Académie des arts martiaux médiévaux européens</b> or <b>AEMAM</b> a dirigé la recherche et le développement, la formation et l'enseignement des arts martiaux européens historiques (HEMA) <sup><a href=\"#1\" title=\"référence n° 1 : HEMA\">[1]</a></sup> <sup><a href=\"#2\" title=\"référence n° 2 : HEMAC\">[2]</a></sup> depuis 1998 et est la plus ancienne académie HEMA du Canada. AEMMA n'a jamais renoncé à sa mission et continuera d'évoluer, de développer, de former et de donner des cours à HEMA aux étudiants, à une formation authentique en arts martiaux et à un environnement unique de conditionnement physique et de formation sans précédent au Canada. Situé dans le centre-ville de Toronto dans l'annexe à l'angle de Dupont et Ossington est facilement accessible via TTC, voiture, vélo ou à pied. ";
$new_1_p2[1]	= "Si vous êtes nouveau dans le monde de l'HEMA et que vous êtes intéressé à suivre une formation dans l'art ancien, le programme d'introduction à l'<i>Armizare</i> est un excellent moyen de déterminer si HEMA est pour vous tout en encourant un minimum Frais de formation et d'équipement. Vous apprendrez dans le programme des informations sur l'histoire d'<i>Armizare</i>, Maestro Fiore dei Liberi (le maître d'épée qui a écrit les traités sur l'art de combat), sources d'étude et de matériaux et fondamentaux sur abraçare (grappling), Daga (poignard) et spada (épée). Les étudiants qui terminent avec succès le cours d'introduction le qualifient pour se joindre à l'Académie et s'inscrivent au programme de formation régulière au grade de recruteur, premier rang dans la formation à long terme en l'<i>Armizare</i>. ";

$title_2[1] = "Exigences d'équipement pour l'introduction à l'arte dell'armizare (Armizare)";
$new_2_p1[1] = "La liste suivante est le matériel de formation minimum requis pour toute personne intéressée à commencer avec le programme de formation initiale :";
$new_2_l1[1] = "un t-shirt / chemise de formation confortable (les T-shirts de formation d'AEMMA sont disponibles @ 20,00 $ et peuvent avoir certains en stock à la salle d'armes pour l'achat),";
$new_2_l2[1] = "leggings / sweats / short confortables (été seulement),";
$new_2_l3[1] = "chaussures de course ou bottes de lutte / boxe à semelles plates,";
$new_2_l4[1] = "paire de gants de jardin en cuir ou similaire.";
$new_2_p2[1] = "Des armes sont fournies (poignards, épées). De toute évidence, les besoins en équipement nécessiteront peu ou pas d'investissement si vous avez déjà les éléments mentionnés.";

$title_3[1] = "Horaire et frais";
$new_3_p1[1] = "<b>Horaire : </b>Le programme d'introduction est programmé tous les deux mois et commence le premier lundi de ce mois et est programmé deux fois par semaine pendant quatre (4) semaines <b>le lundi et le mercredi de ".$intro_armizare_start_time[1]." à ".$intro_armizare_end_time[1].".</b> Les programmes d'introduction sont programmés pour commencer en janvier, mars, mai, juillet, septembre et novembre.</p><p><b>Frais : </b><b style = 'color: green;'>".$intro_fee." $</b> (tous dans). Les frais sont payables via Paypal à l'Académie (via le Collectif des Arts Combattants <sup><a href=\"#3\" title=\"référence n° 3: FACT\">[3]</a></sup>) en cliquant sur le bouton Paypal. Paypal accepte les cartes de débit / crédit via une transaction Paypal sécurisée.";
$new_3_p2[1] = "Après avoir soumis un paiement à l'Académie en utilisant la méthode Paypal, cliquez ici pour envoyer un courriel à l'Académie confirmant que vous avez effectué votre paiement, et indiquez votre nom complet, adresse, téléphone, courriel et le mois où vous souhaitez commencer votre Formation initiale. Vous serez contacté par l'Académie par email / téléphone pour confirmer la réception et votre inscription au programme.";

$new_3_l1[1]	= "Les arts martiaux européens historiques (HEMA) se réfèrent aux arts martiaux d'origine européenne, en particulier en utilisant des arts autrefois pratiqués, mais ayant depuis disparu ou évolué dans des formes très différentes. Le terme arts martiaux occidentaux (WMA) est parfois utilisé aux États-Unis et dans un sens plus large incluant les disciplines modernes et traditionnelles. À la fin du Moyen Âge, la longue épée avait une position d'honneur parmi ces disciplines, et parfois l'épée européenne historique (HES) est utilisé pour se référer spécifiquement aux techniques d'épée. source : Wikipedia. <a href=\"https://fr.wikipedia.org/wiki/Arts_martiaux_historiques_europ%C3%A9ens\" target=\"_blank\">Arts martiaux historiques européens</a>. consulté le : 17 janvier 2017.";
$new_3_l2[1]	= "La Coalition historique des arts martiaux européens (HEMAC) est une collection d'artistes et de chercheurs martiaux en Europe. Ils se consacrent à l'étude, à la reconstruction, à la pratique et à la promotion des arts de combat européens traditionnels, sur la base de l'étude des sources techniques survivantes (traités et manuels). HEMAC a été créé en 2001 et est une organisation non hiérarchique, de tables rondes, composée de chercheurs individuels et d'artistes martiaux de nombreux groupes à travers l'Europe. source : <a href=\"http://www.hemac.org/\" target=\"_blank\" title=\"HEMAC\">HEMAC</a>. consulté le : 17 janvier 2017.";
$new_3_l3[1]	= "Fighting Arts Collective est la principale école combative d'arts martiaux à Toronto spécialisée dans les solutions réelles, le contexte historique et les programmes de conditionnement physique non conventionnels. Fondée en 2004 par des instructeurs de renommée mondiale, FACT s'engage à respecter les valeurs de la collaboration, de la vie saine et de la poursuite de la guerre. Ils ont actuellement 9 écoles d'enseignement de 8 arts martiaux, les compétences en armes, plusieurs programmes de conditionnement physique et une école aérienne. Ils organisent également des ateliers, des événements et des séminaires avec des instructeurs locaux et internationaux. source: <a href=\"http://www.fightingartscollective.com\" target=\"_blank\">Fighting Arts Collective Toronto</a>. consulté le : 17 janvier 2017.";

?>
