<?php
// Program: content_arte_fiore_dei_liberi_en.php
//	Description: source for the English textual content for the overview of Fiore dei Liberi (arte_fiore_dei_liberi.php)
//	2017 ------------------
//
// English content -------------------
$title[0] = "About Maestro Fiore dei Liberi";
$arte_fiore_dei_liberi_caption[0] = "An image of the first page of the prologue found in the Pisani-Dossi version of Flos Duellatorum. Click to view larger image of the prologue.";
$arte_fiore_dei_liberi_prologue_title[0] = "Click to view larger image of the prologue.";
$arte_premariacco_caption[0] = "The coat of arms of the village of Premariacco. Premariacco is a comune in the province of Udine in the Italian region Friuli-Venezia Giulia, located about 60 kilometres northwest of Trieste and about 13 kilometres east of Udine.";
$arte_premariacco_title[0] = "Click to visit the community of Premariacco's website";
$arte_p1[0] = "Despite the significant impact Fiore's treatise has had on the modern reconstruction of historical fighting arts, in particular, armizare, very little is known of the man who bore the name Fiore dei Liberi. To date, given the extensive and ongoing research being conducted world-wide by a variety of historical fencing schools and academies the only definitive source for Fiore's biography has been the prologue written by Fiore himself contained in three versions of the treatise. ";
$arte_p2[0] = "The treatise, authored by Fiore himself, styles himself as \"<i>Fior Furlan de Ciuida dostria</i> \" in the Getty's prologue <sup><a href=\"#1\" title=\"Reference #1: Getty\">[1]</a></sup>, \"<i>Fiore Furlan de Ciuida dostria</i> \" in the Morgan's version <sup><a href=\"#2\" title=\"Reference #2: Morgan\">[2]</a></sup> and \"<i>Fior furlano dei liberi de Ciuidal dostria</i> \" in the \"<i>alter prologus</i> \" in the Pisani-Dossi (PD) version <sup><a href=\"#3\" title=\"Reference #3: Pisani Dossi\">[3]</a></sup>. The PD phrase translates into \"Fiore Friuli of the family of the Liberi from Cividale d'Austria\" which is commonly abbreviated to \"<i>Fiore dei Liberi</i> \". The prologue tells us that Cividale d'Austria was part of the Diocese of Aquileia and that he was born the son of \"<i>meser benedetto de la casada dei liberi da premergiago</i> \" translated as \"Sir Benedetto of the House of the Liberi from Premariacco\". The village of Premariacco <sup><a href=\"#4\" title=\"Reference #4: Premariacco\">[4]</a></sup> and Cividale d'Austria (now Cividale del Friuli) both exists today and reside in an area known as \"Friuli\", an area with its own unique cultural and historical identity. Cividale del Friuli is the last known residence of Fiore based on the extracts from the prologues. ";
$arte_p3[0] = "Fiore does not reveal his birth date nor year in any version of the treatise, however, it is estimated that Fiore was born sometime around 1350. This estimated year becomes more apparent upon further examination of the text extracted from the prologue. He wrote that he had possessed a natural combative ability at a young age, having left his village of Premariacco to learn more advanced fencing techniques and to increase his skills by traveling to many provinces, training under many Italian and German masters. He stated that he had been training and fighting for more than 40 years, and given the timing when he started writing the treatise on 10 February, 1409 and the assumption that he started training and fencing at the age of 10 years, would make Fiore somewhere around sixty years of age at the time of writing the treatise. ";
$arte_p4[0] = "Without a doubt, the most vexing part of Fiore's life were his later years, at the end of the 14th century and the beginning of the 15th century during the period of time of the composition of his treatise or treatises. The \"<i>alter prologus</i> \" in the Pisani-Dossi version highlights Nicolo III d'Este and Marquis of Ferrare and mentions that the composition of the treatise including both the writing and the illustrations were at the request of Nicolo. This implies that Nicolo was Fiore's Patron and therefore commissioned Fiore to compose a book on combat to satisfy Nicolo's desire to add to his extensive bibliographic collection. There is nothing in the prologue which may indicate that Fiore was a member of the Marquis's court and given Fiore was a reputable and notable swordsman, Nicolo's library was enhanced with the addition of Fiore's treatise which he started writing on February 10, 1409 and completed the treatise some six months later.";

$arte_l1[0] = "<b><i>Fior di Battaglia</b></i>: MS Ludwig XV 13 - <a href=\"http://www.getty.edu/art/collection/objects/1443/unknown-fiore-furlan-dei-liberi-da-premariacco-il-fior-di-battaglia-italian-about-1410/\" target=\"_blank\" title=\"J. Paul Getty Museum (codice 'GETTY')\">J. Paul Getty Museum (codice \"GETTY\")</a>";
$arte_l2[0] = "<b><i>Fior di Battaglia</b></i>: MS M.383 - <a href=\"http://ica.themorgan.org/manuscript/page/1/77302\" target=\"_blank\" title=\"The Pierpoint Morgan Library (codice 'MORGAN')\">The Pierpoint Morgan Library (codice \"MORGAN\")</a>";
$arte_l3[0] = "<b><i>Flos Duellatorum (Pisani-Dossi MS)</b></i>: <a href=\"http://wiktenauer.com/wiki/Flos_Duellatorum_(Pisani_Dossi_MS)\" target=\"_blank\" title=\"Pisani-Dossi MS (codice 'Pisani-Dossi MS')\">F. Novati, Flos duellatorum</a>: Il Fior di battaglia di maestro Fiore dei Liberi da Premariacco (Bergamo, 1902)";
$arte_l4[0] = "Premariacco (Friulian; Premariâs) is a comune (municipality) in the province of Udine in the Italian region Friuli-Venezia Giulia, located about 60 kilometres (37 mi) northwest of Trieste and about 13 kilometres (8 mi) east of Udine. Premariacco borders the following municipalities: Buttrio, Cividale del Friuli, Corno di Rosazzo, Manzano, Moimacco, Pradamano, Remanzacco. Paulinus II of Aquileia, the Patriarch of Aquileia and one of the most eminent scholars of the Carolingian Renaissance, was established in Premariacco around 726. source: Wikipedia. <a href=\"https://en.wikipedia.org/wiki/Premariacco\" target=\"_blank\">Premariacco</a>. Retrieved: January 17, 2017.";
?>
