<?php
ini_set('display_errors', 'On');
// 	Program: 	members_changePW.php
//	Description: 	This scripts provides the browser the function to change one's password. Passwords are encrypted in the database.
//	Author:		David M. Cvet
//
//	2016 ----------
//	aug 16:	adjusted the code to support preferred principle name, turned it into a session variable
//	sep 01: enhanced the change password subroutine call to accept a return value from DB.php on the success/failure of the password change
//	sep 02: test for using "password" for the AIMS login, and if so, send user to this change password program
//	sep 08:	added AIMS variable, which will either maintain the AIMS drop-down menu, or revert it to pre-AIMS login
//
if (isset($_GET['AIMS'])) {$aims = $_GET['AIMS'];} else {$aims = 0;}
// check for the PHP parameter MSG, which is set only if the password change has been successful, in order to inform the browser
// that the password has been changed on the change password window
if (isset($_GET['MSG'])) {$msg = $_GET['MSG'];} else {$msg = "";}

$lang = "en";
$lang_num = 0;
$members_only_path = "../";			// the location of the members only scripts and files with respect to this calling script
$dbase_path = "../database/";			// the location of the database scripts and files with respect to this calling script
$current_pgm = "members_changePW.php";
$menu_selected = "resources";
//$content = "../";
$ss_path = $dbase_path."ss_path.stuff"; include "$ss_path";
$db_path = $dbase_path."DB.php"; include "$db_path";
session_start();
// test to determine if the initial database login session remains intact or the session has timed out before attempting to connect with the database
$session_expiration = $members_only_path."php-bin/sub_check_session_expiration.php"; include "$session_expiration";

//$idvalid = $dbase_path."IDValid.php"; include_once "$idvalid";
$retrieve = $members_only_path."php-bin/retrieve_cookies.php"; include "$retrieve";

$config = $members_only_path."config/config.php"; include "$config";
$config_pwd = $members_only_path."config/content_members_changePW_$lang.php"; include "$config_pwd";
$header = $members_only_path."php-bin/members_only_header.php"; include "$header";
//echo ('debug:members_changePW:20:aims="'.$aims.'"'); //(at this point, when password is password for AIMS login, the AIMS is set to "0", which alters the menu for AIMS)
echo ('<script type="text/javascript" src="'.$members_only_path.'../js-bin/beep.js"></script>');
$header2 = $members_only_path."php-bin/members_only_header2.php"; include "$header2";
?>
	<!-- begin main content container -->
	<div id="main_content_mo">
<?php
	if (isset($_POST['OldPW'])) 
		{
		if ($_POST['NewPW1'] != $_POST['NewPW2'])
			{
			$msg = $pw_error_1[$lang_num]; 
			echo ('<script type="text/javascript">new Beep(22050).play(1200, .15, [Beep.utils.amplify(19000)]); new Beep(22050).play(800, .25, [Beep.utils.amplify(19000)]);</script>');
			}
		elseif ($_POST['OldPW'] == $_POST['NewPW1'])
			{
			$msg = $pw_error_2[$lang_num]; 
			echo ('<script type="text/javascript">new Beep(22050).play(1200, .15, [Beep.utils.amplify(19000)]); new Beep(22050).play(800, .25, [Beep.utils.amplify(19000)]);</script>');
			}
		else
			{
			$LinkID=dbConnect($DB);
			$success = ChangePW($LinkID, $_POST['OldPW'], $_POST['NewPW1']);
			dbClose($LinkID);
//echo ('debug:members_changePW:45:success="'.$success.'"');exit;
			if ($success == 1) 
				{
				$msg = $pw_OK[$lang_num]; 
				}
			elseif  ($success == 2)	
				{
				$msg = $pw_not_OK[$lang_num];
				echo ('<script type="text/javascript">new Beep(22050).play(1200, .15, [Beep.utils.amplify(19000)]); new Beep(22050).play(800, .25, [Beep.utils.amplify(19000)]);</script>');
				}
			else
				{
				$msg = $pw_problems[$lang_num];
				echo ('<script type="text/javascript">new Beep(22050).play(1200, .15, [Beep.utils.amplify(19000)]); new Beep(22050).play(800, .25, [Beep.utils.amplify(19000)]);</script>');
				}

			echo ('<script type="text/JavaScript">');
			echo ('parent.location.href="members_changePW.php?MSG='.$msg.'"');
			echo ('</script>');
			}
		}
	else	
		{
		if ($msg == "")
			{$msg = $pw_p1[$lang_num];} // if the message is generated by AIMS, then the variable $msg would've been blank and would now be assigned the AIMS message
		else
			{
			// this indicates that the change password function was invoked by a login, as this prevents the user from logging in using password set to "password"
			echo ('<script type="text/javascript">new Beep(22050).play(1200, .15, [Beep.utils.amplify(19000)]); new Beep(22050).play(800, .25, [Beep.utils.amplify(19000)]);</script>');
			}
		}
?>
		<p><img src="../images/1090x4_transparent.png" width="100%" alt="" /></p>
		<div class="change_login box">
			<form action="members_changePW.php?AIMS=<?=$aims?>" name="ChangePW" method="post">
			<table border="0" colspan="2" cellpadding="3" style="margin:auto;">
			<tr>
				<td align="center" colspan="2" class="proddesc"><b><u><?=$title[$lang_num]?></u></b><div align="center"><br /><?=$msg?></i></font><br />&nbsp;</div></td>
			</tr>
			<tr>
				<td valign="bottom" align="right" id="Label" class="proddesc">Login ID:</td>
				<td valign="bottom" align="left"><font color="blue"><b><?=$_SESSION["UserID"]?></b></font></td>
			</tr>
			<tr>
				<td valign="center" align="right" id="Label" class="proddesc"><?=$pw_old_pw[$lang_num]?></td>
				<td><input type="password" name="OldPW" size="16" maxlength="16"></td>
			</tr>
			<tr>
				<td valign="center" align="right" id="Label" class="proddesc"><?=$pw_new_pw[$lang_num]?></td>
				<td><input type="password" name="NewPW1" size="16" maxlength="16"></td>
			</tr>
			<tr>
				<td valign="center" align="right" id="Label" class="proddesc"><?=$pw_confirm[$lang_num]?></td>
				<td><input type="password" name="NewPW2" size="16" maxlength="16"></td>
			</tr>
			<tr>
				<td align="center" colspan="2"><br />&nbsp;<br /><input type="reset"  value="<?=$pw_reset[$lang_num]?>"><input type="submit" value="<?=$pw_change_pw[$lang_num]?>" name="OK"><br /><br /></td>
			</tr>
			</table></form>
		</div>
	</div><!-- main_content -->
	<!--- begin footer -->
<?php
$footer_var = $members_only_path."php-bin/footer.php"; include "$footer_var";
?>
	<!-- end footer -->
</div><!-- container -->
</body>
</html>
